mrjob/emr.py, mrjob/runner.py
Messed up the branch earlier, while replying to https://github.com/Yelp/mrjob/pull/964.
This is the same review, updated the warning as mentioned.
=> Deprecated warning

mrjob/compat.py, mrjob/emr.py, mrjob/fs/hadoop.py, mrjob/fs/s3.py, mrjob/hadoop.py, mrjob/job.py, mrjob/launch.py, mrjob/options.py, mrjob/parse.py, mrjob/pool.py, mrjob/runner.py, mrjob/setup.py, mrjob/step.py, mrjob/tools/emr/collect_emr_stats.py, mrjob/util.py, tests/test_local.py, tests/tools/emr/test_collect_emr_stats.py
Address `pep8` and `pyflakes` warnings.
Planning to merge this myself; just want to give Travis CI a chance to run the tests.
=> v0.4.3 style checks

mrjob/launch.py, tests/test_launch.py
=> Don't load boto for hadoop, local runners

mrjob/__init__.py, mrjob/bootstrap/terminate_idle_job_flow.sh
This includes #1163 and fixes some issues with it.
=> use `which yarn` in terminate_idle_job_flow.sh

CHANGES.txt, mrjob/emr.py, mrjob/hadoop.py, mrjob/runner.py, tests/test_emr.py, tests/test_option_store.py, tests/test_runner.py
This fixes #1261. Updated test cases and documentation as well.
=> split REMOTE_TMP into CLOUD_TMP and HADOOP_TMP

docs/guides/emr-quickstart.rst, mrjob/emr.py, mrjob/tools/emr/mrboss.py
Some small fixes to make `mrjob boss` work. Never paid much attention to this command before hand-testing it, and the tests apparently don't do much. Fixes #1282.
=> Fix mrboss

mrjob/tools/emr/s3_tmpwatch.py, mrjob/tools/emr/terminate_idle_clusters.py
Fixes for dumb option-parser mismatches in a couple of mrjob subcommands (fixes #1290)
=> mrjob subcommand fixes

mrjob/hadoop.py, mrjob/inline.py, mrjob/sim.py, tests/test_option_store.py
This fixes two small oversights having to do with options (#1321 and #1322).
=> option combiner fixes

mrjob/logs/log4j.py, tests/logs/test_log4j.py, tests/logs/test_step.py
Looks like there are lots of log4j patterns out there. This change handles a few more, including the one in #1406.
=> improved log4j parsing

mrjob/aws.py, tests/test_aws.py
Rebuilt EC2 instance data, and added one sanity-check that I ran by hand. Fixes #1414.
=> EC2 instance type data refresh

mrjob/emr.py, tests/test_emr.py
=> pooling is case-insensitive for EMR applications

mrjob/dataproc.py, mrjob/emr.py, mrjob/hadoop.py, mrjob/runner.py, tests/test_hadoop.py, tests/test_runner.py
Merged some common code having to do with step input and output URIs. Want this in `master` before I start refactoring relevant Spark code.
=> Step URI refactor

mrjob/emr.py
This allows users to identify and troubleshoot pooling issues and control resource usage on EMR.
=> add debug logging for pooling feature

mrjob/emr.py, tests/test_emr.py
This updates the EMR cluster step limit to 1000 for all but the most ancient AMIs, fixing #1463.
EMR will actually *accept* more steps, but it won't show more than 1000, so we'd have to update usage auditing and pooling's "locking" mechanism to make that work, which would require much more code. See #1462 for details.
=> raise step limit to 1000 for most AMIs

mrjob/emr.py, mrjob/fs/s3.py, mrjob/iam.py, setup.py, tests/mockboto.py, tests/test_emr.py, tests/test_iam.py
This is the first step of moving from `boto` to `boto3` (see #1304).
=> use boto3 for IAM

docs/guides/emr-advanced.rst, docs/guides/emr-opts.rst, mrjob/emr.py, mrjob/options.py, mrjob/tools/emr/create_cluster.py, tests/test_emr.py, tests/tools/emr/test_create_cluster.py
=> rename emr_applications option to applications

mrjob/tools/emr/terminate_idle_clusters.py
=> correctly call _attempt_to_acquire_lock()

docs/guides/emr-opts.rst, mrjob/emr.py, tests/test_emr.py
=> bump default AMI version to 5.8.0

mrjob/emr.py, tests/test_emr.py
This warning used to crash because it tried to `ListInstanceGroups`, which is a no-no for clusters with instance fleets. Fixes #1637.
=> fix spark support warning for instance fleets

mrjob/bin.py, mrjob/emr.py, mrjob/job.py, mrjob/launch.py, mrjob/options.py, mrjob/runner.py, tests/test_bin.py, tests/test_job.py, tests/test_local.py
deprecated get_opts() (fixes #1665), simplified my handling of argparse actions (fixes #1662), and closed a number of TODOs.
=> small tweaks for v0.6.0 release

mrjob/options.py, tests/test_emr.py
=> --check-cluster-every takes a float, not a string

mrjob/pool.py
This adds a lot of type checks to user-created instance_fleets and instance_groups configs in pooling code, with the goal of letting the errors come from `boto3` or the EMR API rather than an exception from inside pool matching.
I didn't add tests because this is just an error-handling issue. Bad fleet/group configs should eventually fail either way.
=> make pool matching robust against bad instance_fleets/instance_groups

docs/runners-emr.rst, docs/runners-runner.rst, mrjob/emr.py, tests/test_emr.py
Expose (and somewhat rewrite) the method that picks a runner's steps out of a cluster. Fixes #1625.
=> expose get_job_steps()

mrjob/local.py, mrjob/options.py, mrjob/sim.py, tests/test_local.py, tests/tools/emr/test_create_cluster.py
Add an option to specify the number of cpu cores while running in local mode.
=> Add option for cpu-core usage for local mode

docs/guides/emr-bootstrap-cookbook.rst
=> note that you can't use sudo in setup commands on EMR

mrjob/dataproc.py, mrjob/emr.py, mrjob/hadoop.py, mrjob/logs/mixin.py, mrjob/logs/step.py, tests/logs/test_step.py, tests/mock_google/dataproc.py, tests/test_dataproc.py
This parsers the job driver output, available on Google Cloud Storage to provide job status (fixes #1671) and counters (fixes #1703).
=> progress logging and counters for Dataproc

mrjob/examples/mr_boom.py, mrjob/inline.py, tests/test_inline.py
=> fix "error while reading from" in inline mode

mrjob/cat.py, mrjob/dataproc.py, mrjob/fs/gcs.py, tests/fs/test_gcs.py, tests/mock_google/case.py, tests/mock_google/storage.py, tests/test_dataproc.py
=> GCS cat() now streams chunks incrementally

mrjob/cloud.py, mrjob/dataproc.py, mrjob/emr.py, mrjob/examples/mr_jar_step_example.py, tests/test_dataproc.py
Fixes #1676, #1677, #1678 (everything in Dataproc parity M5).
=> JarStep and --hadoop-streaming-jar on Dataproc

CHANGES.txt, mrjob/ami.py, mrjob/emr.py, mrjob/options.py, mrjob/retry.py, tests/mock_boto3/case.py, tests/mock_boto3/ec2.py, tests/test_ami.py, tests/test_emr.py, tests/tools/emr/test_create_cluster.py
Added utilities to help with building custom AMIs to use on EMR (fixes #1829)
=> describe_base_emr_images() and make_ec2_client()

mrjob/sim.py
=> Fixing Permission Error [WinError 5] on windows

mrjob/job.py
Whoops, this was supposed to go in in #1949.
=> break out combine_pairs() in MRJob for consistency

.travis.yml, mrjob/hadoop.py, mrjob/local.py, mrjob/logs/step.py, mrjob/runner.py, mrjob/sim.py, setup.py, tests/test_bin.py, tests/test_emr.py, tests/test_hadoop.py, tests/test_local.py
The local runner can simulate running your spark MRJob on a cluster, thanks to `pyspark` and its `local-cluster` master. Fixes #1361.
=> local runner Spark support

mrjob/spark/mrjob_spark_harness.py
=> spark_harness support SORT_VALUES

mrjob/bin.py, mrjob/spark/mr_spark_harness.py, mrjob/spark/mrjob_spark_harness.py, tests/sandbox.py, tests/spark/test_mrjob_spark_harness.py, tests/test_inline.py
Added missing unit tests for Spark harness, including some recent features. Fixes #1948.
Found and fixed couple of issues with implementing `SORT_VALUES` (see #1945). Also changed `--compression-codec-class` to simply `--compression-codec` (see #1963).
=> Spark harness tests

tests/fs/test_hadoop.py, tests/mockhadoop.py
Updated `tests/mockhadoop.py` to emulate `hadoop fs -touchz`, and tested our fs's `touchz()` method. Fixes #1981.
=> test hadoop fs touchz()

mrjob/spark/mrjob_spark_harness.py, tests/spark/test_mrjob_spark_harness.py
Still figuring out how to output the counter result so that it work with `parse_mr_job_stderr`. Send out CR as a early check for potential logic issue.
=> spark_harness_process_increment_counter

mrjob/spark/mrjob_spark_harness.py, mrjob/spark/runner.py, tests/spark/test_mrjob_spark_harness.py, tests/spark/test_runner.py
=> Limit number of  output files in spark_harness_script

setup.py, tests/test_setup_dot_py.py
This ensures that we haven't forgotten to add new packages to `setup.py`. Fixes #2035.
=> Test setup.py package list

README.rst
- Add code highlighting to Python code block
=> Update broken docs link

docs/whats-new.rst
=> Fix simple typo: mrjob-speific -> mrjob-specific

mrjob/emr.py, tests/test_emr.py
=> Set VisibleToAllUsers to true by default

CHANGES.txt, README.rst, docs/guides/configs-all-runners.rst, docs/guides/emr-opts.rst, docs/whats-new.rst, mrjob/__init__.py, mrjob/bin.py, mrjob/cloud.py, mrjob/emr.py, mrjob/examples/mr_text_classifier.py, mrjob/fs/ssh.py, mrjob/runner.py, setup.py, tests/mock_boto3/case.py, tests/mockssh.py, tests/spark/test_harness.py, tests/spark/test_runner.py, tests/test_bin.py, tests/test_emr.py, tests/test_emr_pooling.py, tests/test_local.py
Here is my proposed v0.7.2 release, with updated documentation and pyflakes/pycodestyle fixes.
This includes #2157, which fixes an issue that came up in hand-testing.
@88manpreet: If you like, just let me know if this branch looks good, and I can merge it into master and cut the release. Thanks!
=> proposed v0.7.2 release

CHANGES.txt, README.rst, docs/guides/emr-opts.rst, docs/whats-new.rst, mrjob/__init__.py, mrjob/dataproc.py, mrjob/emr.py, mrjob/inline.py, mrjob/options.py, mrjob/pool.py, mrjob/sim.py, setup.py, tests/test_dataproc.py, tests/test_emr_pooling.py, tests/test_local.py, tests/tools/emr/test_create_cluster.py
Final documentation updates and style fixes for the v0.7.4 release.
This also updates boto3/botocore library versions (fixes #2193) and cleans up some tests of cluster pooling (fixes #2196).
=> v0.7.4 release
