- mrjob/step.py
- tests/test_step.py
When explicitly setting step kwargs as None, i.e. mapper=None, reducer=None, it should not count as having an actual mapper or reducer.
Previously these end up counting as an "identity" process.
> filter out any steps that have their kwarg set to None

- docs/guides/emr-opts.rst
- mrjob/emr.py
- mrjob/options.py
- tests/mockboto.py
- tests/test_emr.py
- tests/tools/emr/test_terminate_idle_job_flows.py
Added test to #911, improved documentation.
Also updated code to use `TERMINATE_CLUSTER` rather than `TERMINATE_JOB_FLOW`, which is deprecated (#974).
> --emr-action-on-failure

- CHANGES.txt
- docs/guides/configs-all-runners.rst
- mrjob/launch.py
- mrjob/options.py
- mrjob/runner.py
- tests/test_runner.py
Backed out the `--job-name` and `--export-job-name` options.
In brief `self._job_name` is meant to be a unique key for the job, and it only used internally. Setting it to a non-unique value causes unexpected behavior.
It seems like it `self._job_name` ought to be the same as the job's name on Hadoop (`mapreduce.job.name`), but it's just confusingly named (see #952).
> Dont mess with self._job_name

- mrjob/emr.py
- mrjob/fs/s3.py
- mrjob/tools/emr/s3_tmpwatch.py
- mrjob/util.py
- tests/fs/test_s3.py
Cleanup of pull request #952.
This gets rid of `mrjob.util.VALIDATE_BUCKET` in favor of a wrapper method, `mrjob.fs.s3._get_bucket()`.
Also fixes a bug where string comparison was used to compare versions of `boto`, and added tests.
> Clean up bucket validation

- docs/guides/emr-opts.rst
- docs/whats-new.rst
- mrjob/emr.py
- mrjob/options.py
- setup.py
- tests/mockboto.py
- tests/test_emr.py
- tox.ini
This is a heavily reworked version of #985 that enables multipart upload for large files (by default, larger than 100MB).
#985 had two (hard-coded options), a threshold to enable multipart uploading, and a minimum part size. I made these the same thing for simplicity.
Tests pass, but I still need to hand-test this change!
> Multipart upload to S3

- CHANGES.txt
- docs/guides/configs-all-runners.rst
- mrjob/sim.py
- tests/sandbox.py
- tests/test_hadoop.py
- tests/test_inline.py
- tests/test_runner.py
This fixes #984 and does away with the weird quirk that mrjob's tests could only pass if mrjob was installed.
Basically this does two things:
* re-enables bootstrapping mrjob in `local` mode (by deleting lines from `mrjob/sim.py`). This *does* change a default, but it isn't a breaking change, and this actually just re-aligns mrjob with its docs
* for the handful of tests where we don't want to bootstrap mrjob, or where we're running some other subprocess that needs mrjob (mock hadoop), we update `PYTHONPATH` so that our version of mrjob comes first.
I also fixed some related docs that happened to have been wrong for a while, now that local/inline mode simulate Hadoop.
> make all tests work without mrjob installed

- README.rst
- docs/guides/emr-opts.rst
- mrjob/aws.py
- mrjob/emr.py
- mrjob/iam.py
- mrjob/options.py
- tests/mockboto.py
- tests/test_emr.py
- tests/test_iam.py
This fixes #999, which prevents mrjob from working for new AWS accounts. It's similar to automatic bucket creation; mrjob only creates IAM objects as needed, and once it's created them, they can be reused.
Also added an `iam_service_role` option and renamed the `iam_job_flow_role` option to `iam_instance_profile` because it's not just out-of-date, it's actually incorrect (IAM instance profiles are different from IAM roles). `iam_job_flow_role` still works; it's just deprecated.
> work with new IAM requirements

- docs/guides/emr-opts.rst
- mrjob.conf.example
- mrjob/emr.py
- mrjob/fs/s3.py
- tests/mockboto.py
Owing to how permissions are handed out here, I have to use aws temporary credentials.
Fortunately aws temporary credentials are already supported by to boto library. So I have exposed this piece of boto functionality with an optional config variable. I have tested this locally and it works for me (tm) :)
Is this patch in an acceptable format? Is this a piece of functionality you are willing to add to this project?
Any feedback is welcome.
Thank you
> Adding in the optional aws_security_token to allow temporary aws credentials to be used.

- mrjob/emr.py
- mrjob/iam.py
- tests/test_emr.py
This implements #1008.
Basically, if someone uses mrjob for the first time, and they have full IAM access, mrjob can just create the service role and instance profile for them.
However, if they're don't have full access to IAM, this approach won't work. In this case, the best we can do is hope they (or someone on their account) has followed [Amazon's instructions on how to create these](http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-iam-roles-creatingroles.html), and just go ahead and try to use them. If this fails (because they haven't been created after all), we give them a URL to show to their admin.
This is against the `v0.4.x` branch because it's going to go into `v0.4.5`, which will be a handful of IAM fixes plus some deprecation warnings. As soon as I merge …
> Fallback IAM role/profile

- CHANGES.txt
- mrjob/iam.py
- tests/mockboto.py
- tests/test_emr.py
- tests/test_iam.py
This implements #1026.
Basically, we're working a little harder than we need to to set up IAM for EMR. We *do* need to create roles and an instance profile, but instead of creating policies, we can simply "attach" ones already in AWS. This is not only simpler, it's better because these "managed" policies are versioned and will be automatically updated to track changes in EMR.
Apparently (based on email conversations with a senior manager on the EMR team), the AWS web interface and CLI are going to work this way soon as well. Once they do, mrjob will be able to find and use the role/profile they create rather than auto-creating its own.
Hand-tested this in addition to updating the unit tests.
> use managed IAM policies

- docs/guides/configs-all-runners.rst
- mrjob/emr.py
- mrjob/local.py
- mrjob/options.py
- mrjob/runner.py
- tests/test_local.py
- tests/test_option_store.py
- tests/test_runner.py
This change decouples `steps_python_bin` from `python_bin`, as requested in #1038.
This also explicitly un-deprecates the `python_bin` and `steps_python_bin` option, which we thought at one time would be superseded by the `interpreter` and `steps_interpreter` options, and makes explicit that these options are only meant for non-Python binaries (bet you didn't know you could write a job in bash!).
Part of the reason to decouple `python_bin` and `interpreter` is that they have different defaults. If we're not using Python, we probably want to use `interpreter` both to read steps from the job locally, and to run it remotely. Whereas, if we *are* using Python, you can't really beat `sys.executable` for running the job locally.
Since setting `interpreter` means you're not using Python, doing …
> python_bin and interpreter options

- docs/guides/emr-opts.rst
- mrjob/emr.py
- mrjob/options.py
- setup.py
- tests/mockboto.py
- tests/test_emr.py
The long-awaited change to visible_to_all_users (see #930).
This also bumps the version for boto (see #980), which is part of the plan for v0.5.0. I was hoping to use `run_jobflow()`'s new `visible_to_all_users` keyword, but this would keep the `emr_api_params` option from overriding `VisibleToAllUsers` as suggested by the mrjob documentation (boto sort of broke my `api_params` patch).
> set visible_to_all_users to True by default

- docs/guides/emr-opts.rst
- tests/test_emr.py
The correct parameter to set the EMR job in a specific subnet is Instances.Ec2SubnetId, not Instance.Ec2SubnetId.  While the docs do not explicitly say this is the intention of the parameter, it can be misleading to readers as the correct parameter to pass for this behavior. Instance.Ec2SubnetId gets ignored by the Ec2 API and has no effect.  
I've also updated the tests to reflect the change, since it seemed like the tests and docs were mirroring each other.
> Use Instances.Ec2SubnetId in doc examples

- CHANGES.txt
- mrjob/util.py
- tests/test_emr.py
- tests/test_util.py
In anticipation of supporting non-line-based protocols (see #715), mrjob is undergoing a transition from generators that yield lines to generators that can yield data in arbitrary chunks of bytes. When you want lines, you can wrap said chunk iterators through `mrjob.util.to_lines()`
(`to_lines()` was formerly named `buffer_iterator_to_line_iterator()`, which is more clear, but awkward to use as a wrapper function. The old name will still work until v0.6.0.)
`to_lines()` used to add a trailing newline if the last chunk didn't have one; it now leaves the data unmolested (see #819).
This also lets `mrjob.util.gunzip_stream()` just yield chunks of data rather than lines, as promised in its docstring.
I updated the implementation `to_lines()` to try to be more efficient: instead of appending …
> chunks to lines

- docs/guides/configs-hadoopy-runners.rst
- mrjob/emr.py
- mrjob/hadoop.py
- mrjob/launch.py
- mrjob/options.py
- mrjob/parse.py
- mrjob/runner.py
- mrjob/sim.py
- mrjob/tools/emr/audit_usage.py
- mrjob/tools/emr/terminate_idle_job_flows.py
- tests/test_emr.py
- tests/test_inline.py
- tests/test_runner.py
- tests/tools/emr/test_audit_usage.py
mrjob selects a unique key for each job, which is used for selecting temp directories and "locking" for job flow pooling. Because it contains script and user name, it can also be used to audit usage.
This changes the name of the unique key from "job name" (which is easily confused with Hadoop's job names) to "job key". It also removes code which appeared to allow you to set this key manually, but actually does nothing.
See #982 for why this matters.
> "job key", not "job name"

- docs/guides/emr-opts.rst
- mrjob/emr.py
- mrjob/launch.py
- mrjob/options.py
- tests/mockboto.py
- tests/test_emr.py
This has been asked in https://groups.google.com/forum/#!msg/mrjob/bLGuo4rssds/eWZfKZrSTKQJ.
The third comment in the thread suggests using a **bootstrap action** script in order to have the tags applied. However, I found that solution too cumbersome for something that should be simple to achieve.
Maybe this feature can make it into the 0.5.0 release?
Cheers!
> Add support for applying metadata tags to the EMR cluster right after its creation

- CHANGES.txt
- docs/guides/emr-opts.rst
- mrjob/emr.py
- mrjob/options.py
- tests/mockboto.py
- tests/test_emr.py
For consistency creates an `iam_endpoint` option, analogous to `emr_endpoint` and `s3_endpoint`. (Fixes #1067)
Under normal circumstances, IAM only has a single endpoint, so this mostly exists to support China/GovCloud, or to help people work around weird network issues.
> iam_endpoint option

- mrjob/iam.py
- tests/mockboto.py
- tests/test_emr.py
- tests/test_iam.py
Now that we're on boto 2.35.0, boto's `IAMConnection` has methods for most of the IAM API calls we need. This pull request uses those methods instead of setting up calls manually with `IAMConnection.get_response()`. (Fixes #1062)
This also removes a lot of test code for inline (as opposed to "attached") role policies, which we haven't used since v0.4.5.
> update IAM code to use "new" boto methods

- tests/fs/test_s3.py
- tests/mockboto.py
- tests/sandbox.py
- tests/test_emr.py
- tests/test_hadoop.py
- tests/tools/emr/__init__.py
- tests/tools/emr/test_mrboss.py
- tests/tools/emr/test_report_long_jobs.py
- tests/tools/emr/test_s3_tmpwatch.py
- tests/tools/emr/test_terminate_idle_job_flows.py
Rename `MockEMRAndS3TestCase` (an awkward and incorrect name) to `MockBotoTestCase` and move it to `tests.mockboto`.
Also clean out some unnecessary test case classes and test methods.
> MockBoto test case

- mrjob/emr.py
- mrjob/fs/hadoop.py
- mrjob/hadoop.py
- mrjob/inline.py
- mrjob/local.py
This makes our code much more careful about closing files we've opened, especially pipes to subprocesses.
> Fix resource warnings in tests

- .gitignore
- CHANGES.txt
- mrjob/cmd.py
- mrjob/launch.py
- mrjob/options.py
- mrjob/tools/emr/audit_usage.py
- mrjob/tools/emr/collect_emr_stats.py
- mrjob/tools/emr/create_job_flow.py
- mrjob/tools/emr/fetch_logs.py
- mrjob/tools/emr/job_flow_pool.py
- mrjob/tools/emr/mrboss.py
- mrjob/tools/emr/report_long_jobs.py
- mrjob/tools/emr/s3_tmpwatch.py
- mrjob/tools/emr/terminate_idle_job_flows.py
- mrjob/tools/emr/terminate_job_flow.py
- tests/test_inline.py
- tests/tools/emr/test_create_job_flow.py
- tests/tools/emr/test_fetch_logs.py
- tests/tools/emr/test_job_flow_pool.py
- tests/tools/emr/test_mrboss.py
Someone pointed out on in the Google Group that one of the new IAM options wasn't available in the `create-job-flow` tool (see #1087). Looked over the tools, and found that a lot of options were missing; I think we were mostly expecting people to load options from conf files.
This should add all relevant options to each tool in a way that's somewhat future-proof.
I also stopped using option groups in the tools, and alphabetized (see #1089) command-line switches by their destination throughout (including for mrjobs themselves).
Also added the `mrboss` tool to the `mrjob` command line tool as `mrjob boss`. Deprecated the `job_flow_pool` tool because it's never been part of the `mrjob` command line tool and doesn't seem to do anything particularly useful.
> Add missing tool switches

- mrjob/tools/emr/job_flow_pool.py
- mrjob/tools/emr/terminate_idle_job_flows.py
- tests/mockboto.py
- tests/test_emr.py
- tests/tools/emr/test_terminate_idle_job_flows.py
For some reason, `boto` wraps arguments to steps, which are, [according to the API docs](http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_HadoopStepConfig.html), strings, in objects; the actual string is in the `value` field.
When fixing #876, I paid too close attention to the API docs, and not close enough attention to boto. This fixes incorrect usage of step args in `terminate_idle_job_flows` and updates the tests (see comment at bottom of #876) for the crash.
This also fixes an `ImportError` on the deprecated `job_flow_pool` tool, which was incorrectly importing a function from `mrjob.emr`.
> use correct format for step args

- CHANGES.txt
- mrjob/_boto_emr.py
- mrjob/emr.py
- mrjob/tools/emr/terminate_idle_job_flows.py
- tests/mockboto.py
- tests/test_emr.py
- tests/tools/emr/test_create_job_flow.py
- tests/tools/emr/test_terminate_idle_job_flows.py
Noticed that although `create-job-flows` has an `--emr-tag` switch, tags weren't actually added. Turns out the tag code was added in the wrong place, so that it wouldn't run for persistent job flows. The existing tests for `emr_tags` used mocks directly, not mockboto, so I needed to add that (see #1096).
Also noticed that the `add_tags()` method isn't actually available in the ancient version of boto we're supporting, so added a shim for that.
Unrelated, I noticed that if you run `terminate-idle-job-flows` in dry-run mode, it doesn't actually print out information about which job flows it would terminate. Fixed that (see #1102).
> emr_tags and other fixes

- mrjob/runner.py
This is so setup-wrapper.sh has correct UNIX line endings for AWS EMR. 
Python will write \r\n on Windows when encountering a \n when writing using text mode, which causes jobs to not start on EMR.
> Write as binary mode when outputting setup-wrapper.sh.

- CHANGES.txt
- docs/guides/emr-opts.rst
- docs/guides/emr-quickstart.rst
- mrjob.conf.example
- mrjob/compat.py
- mrjob/conf.py
- mrjob/emr.py
- mrjob/options.py
- mrjob/parse.py
- tests/test_compat.py
- tests/test_parse.py
This get the SSH tunneling behavior that we know and love working on the 3.x AMIs, fixing #1013. These AMIs use Hadoop 2 (a.k.a. YARN), which has a "resource manager" instead of a "job tracker". You can see job progress and download logs from the resource manager, but not get counters. 
We now opening up the tunnel to the correct port, show the correct URL to point the browser at (it has a different path), use "resource manager" or "job tracker" as appropriate in logging messages, and parse the HTML/JS accessible via the tunnel to show job progress. Also renamed `ssh_tunnel_to_job_tracker` to the shorter and more correct `ssh_tunnel` (the old option/switches still work, with a deprecation warning).
EMR has a tantalizing but ultimately unusable proxy to one of the "application servers" for …
> SSH to resource tracker on 3.x AMIs

- mrjob/logparsers.py
- mrjob/parse.py
- tests/test_emr.py
- tests/test_logparsers.py
- tests/test_parse.py
This is part of very slow progress towards getting log fetching/parsing working on the "new" (3.x) AMIs (see #888). This specifically makes it possible to fetch and parse counters via SSH. Hand-tested this, and added some tests for the regexes involved. Basically it boils down to a different filename, and a new, JSON-based format for counters.
Apologies for moving so slowly; the log parsing code is not super good (@irskep, the original author, confirms this ;) ) and I hadn't really taken the time to familiarize myself with it until now.
Also, to make matters worse, mrjob currently can't fetch step logs at all, thanks to EMR now using step IDs rather than step numbers in log paths (see #1117). Will fix that next.
> Fetching counters via SSH from 3.x AMIs

- mrjob/emr.py
- mrjob/hadoop.py
- mrjob/logparsers.py
- mrjob/tools/emr/fetch_logs.py
- tests/test_emr.py
- tests/test_logparsers.py
This fixes #1117.
In brief: log paths for step logs used to use numbers (`1`, `2`, etc.) but now use randomly-assigned step IDs (`s-AAAAAAAA`). This means we need an extra mapping, both to ignore steps that don't matter for our job, and to sort steps in the proper order so that we can find the earliest failure.
> handle step IDs in step log paths

- CHANGES.txt
- mrjob/emr.py
- mrjob/options.py
- tests/test_emr.py
Fixes a bug where we were specifying the default value in the option rather than in the runner, so that "default" always overrode mrjob.conf (see #1070)
> load pool_wait_minutes from mrjob.conf

- CHANGES.txt
- docs/job.rst
- mrjob/examples/mr_postfix_bounce/mr_postfix_bounce.py
- mrjob/job.py
- mrjob/launch.py
- tests/test_job.py
`is_task()` is shorter and more correct (it's `True` for combiners too). Fixes #1072.
> rename is_mapper_or_reducer() to is_task()

- docs/guides/emr-bootstrap-cookbook.rst
- docs/guides/emr-opts.rst
- mrjob/emr.py
- tests/test_emr.py
This enables the `bootstrap_python` option by default for all versions of Python. On Python 2, rather than installing Python 2 (which is already installed), it auto-installs `pip` and `ujson` for you (so that JSON serialization will magically be fast). See #1035.
Unfortunately, Amazon's support for Python 3 is really minimal, and installing `pip` is simpler than `ujson`. Left `bootstrap_python` as-is for Python 3, but added extensive documentation about what you need to do to get `pip` and/or `ujson`.
Also disabled `bootstrap_python_packages` on Python 3.
> Install ujson on Python 2

- docs/guides/configs-hadoopy-runners.rst
- mrjob/compat.py
- mrjob/emr.py
- mrjob/job.py
- mrjob/launch.py
- mrjob/options.py
- mrjob/runner.py
- mrjob/sim.py
- tests/test_compat.py
- tests/test_local.py
- tests/test_runner.py
This change fully relegates `--hadoop-version` to something used only by inline/local mode for version simulation.
`hadoop_version` no longer has a default value. If it's not set, the local/inline runner runs in version-agnostic mode, where when it simulates jobconf variables, it sets them for all possible versions of hadoop. If *you* set jobconf variables, version-agnostic mode leaves them unmolested, rather than patching in their counterparts in the current Hadoop version (see #735 for more details).
This also fixes documentation and `--help` to clarify that inline mode supports jobconf too!
> version-agnostic local mode

- mrjob/hadoop.py
- tests/mockhadoop.py
- tests/test_hadoop.py
Fix `HadoopJobRunner.get_hadoop_version()` on Python 3 (fixes #1142). Basically, we were still treating the output of the `hadoop` command as a `str` rather than `bytes`.
This was masked by a bug in `tests.mockhadoop` combined with `HadoopJobRunner` falling back to an arbitrary version if `hadoop version` produced empty output. Fixed `mockhadoop`, removed the fall-back, and added explicit tests for `get_hadoop_version()`.
> Fix HadoopRunner.get_hadoop_version() in Python 3

- mrjob/compat.py
- mrjob/fs/hadoop.py
- mrjob/hadoop.py
- mrjob/parse.py
- tests/fs/test_hadoop.py
- tests/mockhadoop.py
- tests/test_compat.py
- tests/test_hadoop.py
This makes `HadoopFilesystem.mkdir()` use `-p` when we're on Hadoop 2 (fixes #991).
This required a bit of re-working; it used to be that `HadoopJobRunner` was responsible for figuring out the version of Hadoop we're using, but `HadoopFilesystem.mkdir()` needed version as well, so moved `get_hadoop_version()` from `HadoopJobRunner` to `HadoopFilesystem`.
Also, got rid of the redundant `_mkdir_on_hdfs()` method, and added `mrjob.compat.uses_yarn()`.
> mkdir -p in Hadoop 2

- mrjob/bootstrap/terminate_idle_job_flow.sh
The self-termination script won't fire if other applications (e.g. Spark) are running directly on YARN. Fixes #1145.
> self-termination script respects other YARN applications

- CHANGES.txt
- mrjob/emr.py
- mrjob/fs/base.py
- mrjob/fs/composite.py
- mrjob/fs/hadoop.py
- mrjob/fs/local.py
- mrjob/fs/s3.py
- mrjob/fs/ssh.py
- mrjob/hadoop.py
- mrjob/logparsers.py
- mrjob/py2.py
- mrjob/runner.py
- mrjob/sim.py
- mrjob/tools/emr/s3_tmpwatch.py
- mrjob/tools/emr/terminate_idle_job_flows.py
- tests/fs/test_base.py
- tests/fs/test_hadoop.py
- tests/fs/test_local.py
- tests/fs/test_s3.py
- tests/fs/test_ssh.py
- tests/test_emr.py
- tests/test_hadoop.py
- tests/test_inline.py
- tests/test_launch.py
- tests/test_runner.py
- tests/tools/emr/test_s3_tmpwatch.py
When we broke the runner filesystem out into separate objects in v0.4.0, it was supposedly deprecated to call them on `runner` rather than `runner.fs`, but we didn't add a deprecation warning.
This adds the warning, and fixes all internal calls to access `fs.<method>()` explicitly.
This also renames `path_exists()` and `path_join()` to `exists()` and `join()`.  (`runner.exists(path)` would be confusing, but `runner.fs.exists(path)` is pretty clear.) Also noticed that `join()` was barely used and completely un-tested; re-worked it, and added proper tests.
> Call runner.fs.<method>() explicitly

- docs/conf.py
- docs/guides/configs-basics.rst
- docs/guides/emr-bootstrap-cookbook.rst
- mrjob/conf.py
- setup.py
- tests/test_conf.py
- tests/test_option_store.py
This adds a `!clear` tag to mrjob's YAML config format. When the value of an option is tagged with `!clear`, values of that option included from other config files are ignored. For example:
/etc/mrjob.base.conf:
```yaml
runners:
emr:
setup: do-something
```
/etc/mrjob.conf:
```yaml
include: /etc/mrjob.base.conf
runners:
emr:
setup: !clear do-something else
```
Using `!clear` alone is equivalent to `!clear null` (this is a natural consequence of YAML syntax).
If you specify multiple config files (e.g. with `-c` on the command line), a `!clear` in a later file will override earlier files (`include` is really just a way to add to your list of config files).
You currently cannot do this:
```yaml
include: /etc/mrjob.base.conf
runners:
emr: !clear
...
```
> !clear tag in mrjob confs

- docs/guides/configs-basics.rst
- mrjob/conf.py
- tests/test_conf.py
Deprecated `combine_cmd_lists()` (fixes #1168)
`combine_lists()` can now take strings and scalar values, treating them as single-item lists (fixes #1172)
> List combiners

- mrjob/util.py
- tests/sandbox.py
- tests/test_util.py
This skips `tests.test_util.ArchiveTestCase.test_unarchive_jar()` if there is no `jar` command.
Brought in `which()` from the `hadoop-prefix` branch.
> Skip test if no jar command

- docs/guides/configs-basics.rst
- mrjob/conf.py
- tests/test_conf.py
- tests/test_option_store.py
If you use a relative path in `include:` in a config file, it's now relative to the real path (after resolving symlinks) of the config file.
> relative conf includes

- CHANGES.txt
- mrjob/fs/hadoop.py
- tests/fs/test_hadoop.py
- tests/mockhadoop.py
This makes `HadoopFileSystem.du()` work in YARN as well as pre-YARN, and returns 0 when we try to `du()` a path that doesn't exist (consistent with other filesystems). Fixes #1155.
Turned out to be easier to just use `hadoop fs -du` rather than bothering with `hadoop fs -dus` or `hadoop fs -du -s`. If we ever need to use these, `tests.mockhadoop` is now prepared for that.
> Fix Hadoop du()

- CHANGES.txt
- mrjob/fs/s3.py
- tests/fs/test_s3.py
`S3Filesystem.ls()` and the methods that use it now always try to recurse through "subdirectories" even if the URI lacks a trailing slash (fixes #1183).
> Recursive S3 ls

- CHANGES.txt
- mrjob/fs/composite.py
- mrjob/runner.py
- tests/test_inline.py
- tests/test_local.py
This should eliminate confusion where people try to pass s3:// URIs to their job in local mode, only to have it tell them the URI doesn't exist. Fixes #1185.
> local/inline runner.fs refuses URIs

- mrjob/emr.py
- mrjob/fs/s3.py
- tests/test_emr.py
Don't attempt to clean up jobs that never started, even when pooling job flows.
Don't fail when get_location throws - e.g.
`python -c 'import boto; boto.connect_s3().get_bucket("elasticmapreduce").get_location()'`
> Fix two bugs when running mrjob master:

- CHANGES.txt
- mrjob/emr.py
- mrjob/hadoop.py
- mrjob/local.py
- mrjob/runner.py
- mrjob/sim.py
- mrjob/tools/emr/fetch_logs.py
- tests/fs/test_hadoop.py
- tests/mockhadoop.py
- tests/test_hadoop.py
- tests/test_local.py
In YARN, the `hadoop jar` command prints the counters to stderr. This change allows us to parse and save them, fixing #1153.
Also:
* hid `MRJobRunner.print_counters()` and made it use 0-indexed step numbers (it was 1-indexed for some reason). 
* reworked `mockhadoop` (tired of adding an environment variable for every new feature)
> Hadoop counters

- CHANGES.txt
- mrjob/fs/local.py
- mrjob/hadoop.py
- mrjob/logs/interpret.py
- mrjob/logs/ls.py
- mrjob/logs/parse.py
- mrjob/util.py
- tests/logs/test_interpret.py
- tests/logs/test_ls.py
- tests/logs/test_parse.py
- tests/test_hadoop.py
This change allows us to find probable cause of job failure in pre-YARN logs, by looking at job syslogs and stderr (though that's not so useful without some sort of log aggregation).
This also uses `followlinks=True` with `os.walk()`, so we can read logs from dirs that are symlinked to.
> Pre-YARN task log parsing

- docs/guides/configs-hadoopy-runners.rst
- mrjob/hadoop.py
- mrjob/logs/__init__.py
- mrjob/logs/counters.py
- mrjob/logs/history.py
- mrjob/logs/ids.py
- mrjob/logs/ls.py
- mrjob/logs/parse.py
- mrjob/logs/util.py
- mrjob/logs/wrap.py
- mrjob/py2.py
- tests/logs/test_history.py
- tests/logs/test_ls.py
- tests/logs/test_parse.py
- tests/logs/test_wrap.py
- tests/test_hadoop.py
This change allows `HadoopJobRunner` to fetch counters on pre-YARN Hadoop (and YARN, if it somehow can't parse them from the Hadoop command's stderr). This fixes #1207.
This is all thanks to a partial refactor, which `mrjob/logs/__init__.py` explains and of which only `mrjob.logs.history` is completed (see  #1123). But it works, and it doesn't break anything, so going to push now, and finish the refactor next.
This change also gives us the ability to parse errors from history logs (both YARN and pre-YARN).
> Fetch counters in pre-YARN Hadoop

- mrjob/logs/ls.py
AWS EMR 3.11.0 creates compressed job logs.
Therefore, the regexp for job uri should accommodate S3 objects that end in `.gz`
> Job logs on AWS EMR 3.11.0 are compressed.

- mrjob/emr.py
- mrjob/hadoop.py
- mrjob/local.py
- mrjob/logs/counters.py
- mrjob/runner.py
- mrjob/sim.py
- tests/logs/test_counters.py
- tests/test_local.py
This replaces `runner._print_counters()` with appropriate calls to `mrjob.logs.counters._format_counters()` (fixes #1220).
> Replace _print_counters()

- docs/guides/runners.rst
- mrjob/emr.py
- mrjob/hadoop.py
- mrjob/launch.py
- mrjob/local.py
- mrjob/step.py
- tests/test_emr.py
- tests/test_hadoop.py
- tests/test_launch.py
- tests/test_local.py
- tests/test_step.py
When the local, Hadoop, and EMR runners have a step that fails, they raise `mrjob.step.StepFailedException` rather than a plain `Exception` or `CalledProcessError`. `MRLauncher.run_job()` catches `StepFailedException` and exits so that logging messages aren't obscured by a stacktrace somewhere inside the runner.
(The inline runner just passes job exceptions straight through, so it doesn't have the problem of stacktraces inside the runner distracting from stacktraces inside the job.)
Embarassingly, noticed that we weren't properly streaming S3 log dirs. Made a note of it in #1221.
> StepFailedException

- docs/guides/emr-quickstart.rst
- mrjob/emr.py
- mrjob/hadoop.py
- mrjob/step.py
Issue a friendly warning when users have a problem with their SSH keys because we've changed the default region out from under them.
More testing would be useful here, but should probably wait until after the log interpretation refactor (see #1221).
> Key pair warning

- docs/guides/emr-bootstrap-cookbook.rst
the debian squeeze base used in the 2 AMI is an unsupported debian with an unsupported openssl
> List the 3 and 4 AMIs before the 2 AMI in the docs

- mrjob/emr.py
- mrjob/logs/mixin.py
- mrjob/logs/step.py
- tests/logs/test_mixin.py
- tests/logs/test_step.py
- tests/test_emr.py
Account for EMR breaking the step log into pieces, and add missing unit tests for EMR functions in `mrjob.logs.step`.
> Step log rotation

- mrjob/emr.py
- tests/mockboto.py
- tests/test_emr.py
EMR only updates logs on S3 every 5 minutes, so... we now wait five minutes (or wait for the cluster to terminate, if it's doing that) before parsing logs on S3 (fixes #1236).
We also tell people they can ctrl-c if frustrated, or skip the wait entirely next time by setting up SSH.
> Wait for s3 logs

- mrjob/conf.py
- mrjob/emr.py
- mrjob/runner.py
- tests/mockboto.py
- tests/test_emr.py
This fixes log fetching on the 4.x AMIs, which put the history and task logs in radically different places (but at least make them available).
Also cleaned up status logging for the EMR runner to my satisfaction (see #1044).
> 4.x log fetching

- docs/guides/emr-opts.rst
- mrjob/emr.py
- tests/test_emr.py
This disables `bootstrap_python` and `bootstrap_python_packages` on the 2.x AMIs, since `apt-get` no longer works there (fixes #1248).
This doesn't yet update the docs (will do that when in a more literary frame of mind).
> Stop apt-getting

- docs/runners-emr.rst
- mrjob/conf.py
- mrjob/emr.py
- mrjob/fs/hadoop.py
- mrjob/hadoop.py
- mrjob/local.py
- mrjob/logs/wrap.py
- mrjob/runner.py
- mrjob/sim.py
- tests/logs/test_wrap.py
- tests/test_emr.py
- tests/test_inline.py
- tests/test_local.py
- tests/test_runner.py
Went over every `log.*()` call that runners make, and make them as consistent and non-noisy as possible (see #1044).
Also checked off the last few items on my pre-release TODO list (see #1233)
This is (hopefully) the last feature change before the v0.5.0 release.
> Clean up status logging

- mrjob/emr.py
- tests/test_emr.py
If we have `ec2_key_pair` set and use pooling, we should only join clusters with the same key pair (see #1230).
This builds on pull request #1239.
> Respect key pairs when pooling

- mrjob/emr.py
This PR should fix issue #1230. 
Sorry there are no tests for this particular feature, I couldn't quickly figure out how to trigger this behavior in the test suite, but it's been hand tested. 
If this is not useful please ignore.
> Don't join an EMR cluster with a different ec2_key_pair.

- CHANGES.txt
- docs/guides.rst
- docs/guides/py2-vs-py3.rst
- docs/whats-new.rst
Updated `CHANGES.txt` and `whats-new.rst`. Also added a document summarizing the differences between Python 2 and Python 3 (fixes #1033).
> Whats new in mrjob 0.5.0

- docs/guides/configs-hadoopy-runners.rst
- docs/whats-new.rst
Pretty much everything in `CHANGES.txt` is now reflected somewhere in "What's New"
The main point of this was to list everything that's been deprecated (so I can help Yelp migrate).
> updates to "What's New in 0.5.0"

- CHANGES.txt
- docs/guides/configs-all-runners.rst
- docs/guides/emr-bootstrap-cookbook.rst
- docs/protocols.rst
- docs/whats-new.rst
- mrjob/protocol.py
- tests/test_protocol.py
Restore support for ``simplejson``, and use it if ``ujson`` isn't installed (fixes #1266).
> Restore simplejson

- CHANGES.txt
- docs/guides/configs-all-runners.rst
- mrjob/emr.py
- tests/mockboto.py
- tests/test_emr.py
This makes EMR choose `python2.6` or `python2.7` as appropriate when you're using Python 2 on EMR (fixes #1265).
Also, if the user sets `ami_version` to "latest", fix that up front so that the rest of the code can be simpler (see #1269).
> EMR python_bin defaults

- CHANGES.txt
- docs/guides/emr-bootstrap-cookbook.rst
- docs/guides/emr-opts.rst
- docs/whats-new.rst
- mrjob/emr.py
- tests/test_emr.py
The `bootstrap_python` option is now only responsible for installing Python, not `ujson`. It *does* now install headers and pip (hadn't realized these packages were available for Python 3 before). (Fixes #1264)
This also makes ``bootstrap_python_packages`` run regardless of Python version. We use `python -m pip ...` rather than `pip ...` because it's a little more straightforward to install packages for the correct version of Python. (Fixes #1263)
> bootstrap_python simplification

- docs/whats-new.rst
Other places you might want to revisit:
* http://mrjob.readthedocs.org/en/latest/guides/runners.html#running-on-your-own-hadoop-cluster (describes Hadoop setup)
* http://mrjob.readthedocs.org/en/latest/guides/writing-mrjobs.html#multi-step-jobs (refers to `mr()` several times)
> Fix typos in release notes

- docs/guides/emr-opts.rst
- mrjob/emr.py
- mrjob/py2.py
When you run a job on EMR in verbose mode (`-r emr -v`), `ssh_bind_ports` takes up several lines, making it difficult to read the values of other options.
This replaces the default list with a `range` object (`xrange` on Python 2). Hand-tested on Python 2 and Python 3. Fixes #1284
> use (x)range for ssh_bind_ports default

- docs/guides/configs-hadoopy-runners.rst
- mrjob/job.py
- mrjob/launch.py
- mrjob/options.py
- mrjob/runner.py
- tests/mr_sort_values.py
- tests/test_compat.py
- tests/test_emr.py
- tests/test_job.py
- tests/test_runner.py
This patches a major bug that was disabling `SORT_VALUES` (see #1294).
`SORT_VALUES` now sets both Hadoop 1 and Hadoop 2 jobconf variables, to avoid translation warnings (see #1286)
I also noticed that a method in `mrjob.runner` was doing almost the same thing as `mrjob.compat.translate_jobconf_dict()` so I removed it and added (missing) tests for `translate_jobconf_dict()`.
> fixes to partitioner and SORT_VALUES

- mrjob/logs/history.py
- tests/logs/test_history.py
This fixes #1288 by only parsing errors from the history file if they have non-blank error messages and correspond to `FAILED` (not `KILLED`) task attempts.
> Wrong task error

- mrjob/tools/emr/terminate_idle_clusters.py
- tests/mockboto.py
- tests/tools/emr/test_terminate_idle_clusters.py
This fixes failing tests, and an edge case where a cluster started with boto 2.40.0 with debugging but no steps will be considered a non-streaming step and not marked idle by `terminate_idle_clusters` (see #1306).
> Debug jar issues

- mrjob/conf.py
- tests/test_conf.py
When we changed over to making includes relative to the including file (see #1179), we forgot that a path like `~/your.mrjob.conf` would get joined *before* the `~` could be expanded, so we get nonsense like `/including/dir/~/your.mrjob.conf` rather than `/home/you/your.mrjob.conf`.
This fix moves the call to `expand_path()` to the correct place. Fixes #1308.
> Tilde in include

- mrjob/emr.py
Looks like accidentally broke SSH tunneling to VPCs when I added support for Hadoop 2 (see #1311).
This reverts my offhand, somewhat pedantic change to ssh tunneling back to the way it's always been.
> use localhost, not *host*, for destination of SSH tunnel (fixes #1311)

- mrjob/tools/emr/audit_usage.py
- mrjob/tools/emr/create_job_flow.py
- mrjob/tools/emr/report_long_jobs.py
- mrjob/tools/emr/terminate_idle_job_flows.py
- mrjob/tools/emr/terminate_job_flow.py
This makes it possible to run deprecated tools modules (e.g. `python -m mrjob.tools.emr.create_job_flow`), which was broken by a silly argument-defaulting issue.
Also made the `main()` method in *every* tool take a single argument (named `args` or `cl_args`), which is defaulted to `None`. This removes the `now` keyword argument in `report_long_jobs`, which appears to be unused.
> fix deprecated tools modules

- CHANGES.txt
- docs/whats-new.rst
- mrjob/emr.py
- mrjob/ssh.py
This walks back #1313 so that it only affects 2.x AMIs. Looks like using *host* and not `localhost` was the right thing to do for everything but the (deprecated) 2.x AMIs.
Also, tangentially related, updated debugging logging for `SSHFilesystem` so that it logs a command line like the SSH tunneling code, rather than a raw array of arguments (this turned out to be a nuisance when diagnosing #1287).
> 4.x resource tracker

- mrjob/emr.py
- mrjob/tools/emr/audit_usage.py
- mrjob/tools/emr/report_long_jobs.py
- mrjob/tools/emr/terminate_idle_clusters.py
- tests/mockboto.py
- tests/test_emr.py
- tests/test_hadoop.py
Update code to correctly reflect that the `ListSteps` and `ListClusters` EMR API calls return in reverse chronological order. This was a serious issue with `ListSteps` (the change fixes #1316). It didn't seem to matter at all for `ListClusters`, but now `mockboto` is correct (we were previously ordering by cluster ID).
Our code doesn't rely on any particular order from `ListInstanceGroups` (basically treats it as a dictionary), so rather than trying to make `mockboto` correct, just added comments to warn about relying on ordering.
Also confirmed that `ListBootstrapActions` lists them in the order they were added (not reverse) and documented that in our code. This is what we expected all along, so our code didn't need to be updated.
> Steps ordering

- mrjob/emr.py
- tests/mockboto.py
- tests/test_emr.py
This uses `-n` (no stdin) with the SSH tunnel (hopefully fixes #1161) and opens the SSH tunnel as soon as we know the cluster is ready (fixes #1115).
> SSH tunnel tweaks

- mrjob/emr.py
- mrjob/logs/bootstrap.py
- mrjob/logs/step.py
- mrjob/logs/task.py
- mrjob/runner.py
- tests/logs/test_bootstrap.py
- tests/logs/test_mixin.py
- tests/test_emr.py
- tests/test_runner.py
Finally, mrjob will tell you why a bootstrap script failed (fixes #370).
Some other minor changes:
* the master bootstrap script now redirects stdout to stderr, like the setup wrapper script
* files with paths like `*.cpython-34.pyc` are no longer included in `mrjob.tar.gz`
Also, a small amount of cleanup to EMR runner and log parsing regexes.
> determine cause of bootstrap script failure

- docs/guides/emr-advanced.rst
- docs/guides/emr-opts.rst
- mrjob/emr.py
- mrjob/options.py
- tests/mockboto.py
- tests/test_emr.py
- tests/tools/emr/test_create_cluster.py
This adds the `subnet` option to the EMR runner and makes pooling respect it.
Also refreshed the docs re: pooling rules and added a missing test of pooling's interaction with the master node setup script (which counts as an extra step).
> subnet option

- docs/guides/configs-hadoopy-runners.rst
- mrjob/hadoop.py
- tests/test_hadoop.py
mrjob now goes the extra mile to find your hadoop log dir. Fixes #1339.
> more default hadoop log dir paths

- CHANGES.txt
- docs/guides/emr-advanced.rst
- docs/guides/emr-opts.rst
- mrjob/conf.py
- mrjob/emr.py
- mrjob/options.py
- mrjob/patched_boto.py
- tests/mockboto.py
- tests/test_conf.py
- tests/test_emr.py
- tests/tools/emr/test_create_cluster.py
This adds the emr_configurations option (fixing #1276), including pooling support.
This would have been much simpler to code in `boto3` (see #1304).
> add emr_configurations option

- mrjob/emr.py
Make this consistent with bootstrap and setup scripts.
Doesn't need to be noted in CHANGES.txt because master node setup is new in this release.
> master node setup script redirects output to stderr

- mrjob/emr.py
- mrjob/runner.py
- tests/test_option_store.py
This prevents the value `aws_secret_access_key` and `aws_security_token` from being debug-logged when in verbose mode, instead showing `'...``.
This also only shows the last 4 characters of `aws_access_key_id` (e.g. `'...WXYZ'`).
Fixes #1353.
None of the other runners seem to have credentials worth obfuscating (`dataproc` does it solely through environment variables), but the `_obfuscate()` method is there to redefine if anyone needs it.
> Hide credentials from debug log

- CHANGES.txt
- docs/guides/writing-mrjobs.rst
- mrjob/emr.py
- mrjob/examples/mr_jar_step_example.py
- mrjob/examples/mr_spark_wordcount.py
- mrjob/examples/mr_spark_wordcount_script.py
- mrjob/examples/spark_wordcount_script.py
- mrjob/hadoop.py
- mrjob/job.py
- mrjob/step.py
- tests/mr_jar_and_streaming.py
- tests/mr_null_spark.py
- tests/mr_spark_script.py
- tests/test_emr.py
- tests/test_job.py
- tests/test_step.py
This defines `SparkScriptStep` and makes it possible to run spark scripts on EMR (with the correct command-line switches, anyway, see https://github.com/Yelp/mrjob/issues/1320#issuecomment-236282396). Fixes #1320.
This also defines `SparkStep` and the machinery for defining spark code right in the `MRJob` class. (Fixes #1360)
Also moved the `INPUT` and `OUTPUT` arg interpolation constants from `mrjob.step.JarStep` to `mrjob.step` because they're generally useful (they're still available from `JarStep` until v0.6.0).
> Spark on EMR

- docs/guides/emr-opts.rst
- mrjob/emr.py
- tests/test_emr.py
Stop installing Python 3 by default on AMI 4.6.0+, because it's already there.
The default for `bootstrap_python` is now `None` instead of `True`, so people can force `yum`-installing the Python 3 packages on 4.6.0+ if they want to (this appears to be harmless, as mrjob v0.5.3 is doing it, and you can still bootstrap successfully).
> Python on 4.x amis

- mrjob/hadoop.py
- mrjob/logs/wrap.py
- tests/test_hadoop.py
Swallow `IOError` from `fs.exists()` during log parsing (fixes #1355).
> stop log parsing from erroring on fs.exists()

- mrjob/emr.py
- mrjob/fs/ssh.py
- mrjob/ssh.py
- tests/fs/test_ssh.py
- tests/mockssh.py
- tests/test_emr.py
- tests/test_ssh.py
This uses `sudo cat` and `sudo ls` over SSH on AMI 4.3.0+, to get around permissions issues for the container logs (fixes #1244).
> Use sudo over SSH

- mrjob/setup.py
- tests/test_setup.py
This updates `UploadDirManager` so that it won't give uploaded files a path that starts with `_` or `.`, since these are ignored by Hadoop's input readers. (Fixes #1200) This doesn't distinguish between input files and those that are used for other purposes, but it seems not to matter (your job never sees the upload path anyway).
This doesn't affect `WorkingDirManager`, so if your setup script etc. expects a filename to start with `_` or `.`, it still will.
> Don't hide (potential) input files

- mrjob/emr.py
- mrjob/tools/emr/audit_usage.py
- tests/tools/emr/test_audit_usage.py
This adds a one-second delay before each API call made by `mrjob audit-emr-usage`, which seems to be enough in practice. (Fixes #1091)
Implemented this as a keyword arg to `mrjob.emr._repeat()` that simply calls `sleep()` before each API call. Fancier sorts of wrappers are possible, but I want to know this is more generally useful first. Also may have to re-implement this once we use boto3 (see #1304), so don't want to get too fancy.
> very basic throttling for audit-emr-usage

- CHANGES.txt
- docs/guides/writing-mrjobs.rst
- docs/job.rst
- mrjob/job.py
- mrjob/launch.py
- mrjob/options.py
- tests/mr_no_runner.py
- tests/mr_runner.py
- tests/test_launch.py
Allow passing through existing options, such as `--runner`. Includes documentation.
Also spruced up existing documentation for option-setting methods (for example, the entry for`configure_options()` was empty).
> pass_through_option()

- mrjob/fs/hadoop.py
When running a word count on local Hadoop cluster, program crashed during cleanup step causing this stack trace:
```
Traceback (most recent call last):
File "word_count.py", line 23, in <module>
MRWordFreqCount.run()
File "/Users/etiennebatise/.virtualenvs/ENV-MRJ/lib/python3.5/site-packages/mrjob/job.py", line 430, in run
mr_job.execute()
File "/Users/etiennebatise/.virtualenvs/ENV-MRJ/lib/python3.5/site-packages/mrjob/job.py", line 448, in execute
super(MRJob, self).execute()
File "/Users/etiennebatise/.virtualenvs/ENV-MRJ/lib/python3.5/site-packages/mrjob/launch.py", line 160, in execute
self.run_job()
File "/Users/etiennebatise/.virtualenvs/ENV-MRJ/lib/python3.5/site-packages/mrjob/launch.py", line 238, in run_job
for line in runner.stream_output():
File …
```
> Fix job crash during cleanup on local hadoop cluster

- mrjob/bootstrap/terminate_idle_cluster.sh
- mrjob/emr.py
- tests/mockboto.py
- tests/test_emr.py
This change makes pooling and cluster idle self-termination play well together by having pooled jobs relaunch if they chose a cluster that was in the process of shutting itself down (fixes #708). (There's a window of a minute or two where this can happen because the EMR API is rather slow to notice.)
Also updated the idle termination script to *only* run on the master node, since if you only have one task node, and it terminates itself, EMR interprets that as a step failure, not a cluster failure.
> recover from pooled cluster self-termination

- mrjob/emr.py
- mrjob/options.py
- tests/mockboto.py
- tests/test_emr.py
- tests/tools/emr/test_mrboss.py
On the 3.x and 4.x AMIs, the SSH tunnel now connects to the (internal) IP that the resource tracker actually listens on. While more correct, the old behavior doesn't seem to have been a problem except for certain VPC setups (see #1397, which this fixes).
Also fixed a bug that made the `--ssh-bin-ports` switch unusable since v0.4.5; apparently no one cared? (see #1402)
Refactored the way we cache information about clusters (e.g. AMI version), so that we don't have to worry about a bunch of attributes.
Finally, added good tests for the core ssh tunneling code, which was formerly completely without tests (see #1281).
> tunnel to correct host for resource tracker

- docs/guides/configs-hadoopy-runners.rst
- docs/guides/emr-opts.rst
- mrjob/emr.py
- mrjob/options.py
- tests/test_emr.py
Deprecates the `hadoop_streaming_jar_on_emr` option (fixes #1405). You can now accomplish the same thing by passing a `file://` URI as `hadoop_streaming_jar`.
> deprecate hadoop_streaming_jar_on_emr

- mrjob/emr.py
- tests/test_emr.py
This restores the `ami_version` alias as a deprecated alias for `image_version` (accidentally removed it entirely in v0.5.4).
> ami_version alias

- CHANGES.txt
- docs/guides.rst
- docs/guides/emr-opts.rst
- docs/guides/spark.rst
- docs/job.rst
- mrjob/emr.py
- mrjob/step.py
- tests/mr_streaming_and_spark.py
- tests/test_emr.py
This auto-detects when the user is running Spark, and if it is defaults `instance_type` to `m1.large` rather than `m1.medium`.
This also defaults `instance_type` to `m1.small` on 2.x AMIs, since they don't require `m1.medium`.
Updated the docs, including stub Spark docs
This does *not*:
* auto-install Spark (the docs are a little ahead)
* warn the user if they're using a too-small instance type
> pick cheapest instance type (inc. for Spark)

- mrjob/logs/errors.py
- mrjob/logs/task.py
- tests/logs/test_errors.py
- tests/logs/test_task.py
Update our error picking logic to prioritize task errors (e.g. Python stacktraces), see #1429. Also strip the ever-present `subprocess failed` java stacktrace from task stderr log (see #1430), which makes for less noise and prevents us from showing otherwise empty stderr file contents to the user.
> improve error picking

- mrjob/dataproc.py
- tests/test_dataproc.py
The dataproc runner used a static mapping from image version to Hadoop version, to power `get_hadoop_version()`. (This information isn't available from the API.) This caused a crash when the API reported an unexpected patch version. See #1428 for details.
This uses `map_version()` rather than a dictionary lookup. If we encounter an unknown image version, we'll just return the Hadoop version for the previous known image version.
> handle unknown Dataproc image versions

- docs/guides/configs-hadoopy-runners.rst
- mrjob/emr.py
- mrjob/examples/mr_spark_wordcount_script.py
- mrjob/hadoop.py
- mrjob/options.py
- mrjob/runner.py
- tests/test_hadoop.py
Hadoop runner can now find the `spark-submit` binary and run ``spark`` and ``spark_script`` steps. Fixes #1366.
Hadoop runner now also looks for the hadoop binary, streaming jar (if needed), and spark-submit binary (if needed) up-front, rather than waiting until the last minute.
> Hadoop runner spark support

- mrjob/__init__.py
- mrjob/launch.py
- tests/test_launch.py
Handle the lack of `stdout.buffer` and `stderr.buffer` in Jupyter Notebook. Fixes #1441.
> Jupyter notebook fix

- docs/guides/emr-opts.rst
- mrjob/emr.py
- mrjob/options.py
- tests/test_emr.py
- tests/tools/emr/test_create_cluster.py
This automatically installs Spark on EMR if it looks like your job has Spark steps. Fixes #1367 
You can currently only run a job if your Python version matches `python` on your EMR AMI (since we bootstrap mrjob for whatever version of python matches the local version); this will change with #1370.
> bootstrap Spark

- mrjob/emr.py
- mrjob/hadoop.py
- mrjob/job.py
- mrjob/runner.py
- tests/test_emr.py
- tests/test_hadoop.py
- tests/test_runner.py
Ensure that python binary (see #1370), cmdenv (see #1371), and jobconf (see #1372) are all passed to `spark-submit` with `--conf` options.
> Spark python bin, cmdenv, jobconf

- mrjob/logs/task.py
> Define `task_error` to avoid a possible UnboundLocalError

- docs/guides/configs-hadoopy-runners.rst
- mrjob/options.py
- mrjob/runner.py
- tests/test_runner.py
Add a `spark_args` runner option and `--spark-args` switch.
(This is way easier now that runner options are just a big data structure; see #1460.)
This fixes #1373.
> add spark_args option

- docs/guides/configs-all-runners.rst
- docs/guides/configs-hadoopy-runners.rst
- mrjob/emr.py
- mrjob/hadoop.py
- mrjob/options.py
- mrjob/runner.py
- mrjob/setup.py
- tests/test_emr.py
- tests/test_hadoop.py
- tests/test_runner.py
- tests/test_setup.py
This add support for `--files` and `--archives` in Spark (fixes #1374)
This also adds `--py-file`, which works with both Spark steps and setup scripts (fixes #1375).
Cmdenv now gets passed directly to `spark-submit` by the Hadoop runner (fixes #1464).
Running `mrjob create-cluster --bootstrap-spark` will now pick an `m1.large`, not a `m1.medium` (fixes #1465).
> Spark file support

- mrjob/emr.py
- tests/test_emr.py
Print a warning when attempting to run Spark on an AMI that is too old or an instance that is too small. (Fixes #1424)
Still need to unit-test our warnings.
> Spark warnings

- mrjob/emr.py
- mrjob/hadoop.py
- mrjob/runner.py
- tests/mr_null_spark.py
- tests/test_emr.py
- tests/test_hadoop.py
- tests/test_runner.py
Added support to spark jobs for passthrough args, including file options (fixes #1380).
Also merged common code between Hadoop and EMR runners, vastly improved its structure, and added much more complete tests.
> Spark passthrough args

- mrjob/emr.py
- mrjob/hadoop.py
- mrjob/runner.py
- mrjob/step.py
- tests/mr_spark_jar.py
- tests/test_emr.py
- tests/test_hadoop.py
- tests/test_runner.py
- tests/test_step.py
This lets you run JARs with `spark-submit`, which works almost like running Spark scripts, except that you have to specify a main class, and you can't use ``py_files``. Fixes #1377 
This doesn't add libjar support (see #1469).
> Spark JAR support

- mrjob/logs/mixin.py
- mrjob/logs/task.py
- tests/logs/test_mixin.py
- tests/logs/test_task.py
This change allows us to stop parsing task logs when we find the first task error with a corresponding hadoop error, *or*, if there are no task stderr logs (or we've looked at them all), the first hadoop error. Fixes #1450
> faster task log interpretation

- mrjob/emr.py
- mrjob/parse.py
- tests/test_parse.py
This updates our job tracker and resource manager progress parsers to only parse the status of *running* jobs. (fixes #793). This keeps us from displaying "100%" for a job that has not yet been submitted to Hadoop, or "100%" just before indicating that our job has failed. 
(It also never displays "100%" because that's for *completed* jobs, but that works okay in practice).
This branch also contains a different approach, now reverted, that leaves the parser as-is but ignores "100%" as the first status for a job. Seemed harder to test/maintain, and fixing the parser was straightforward once I dug into it.
> Only load progress of current job

- mrjob/emr.py
- mrjob/parse.py
- mrjob/runner.py
- tests/test_emr.py
- tests/test_parse.py
This fixes a problem where mrjob thought a timestamp was a URI (see #1455).
Also deprecated `is_windows_path()` (since `is_uri()` no longer needs it).
> is_uri() only accepts file-like URIs

- mrjob/emr.py
- mrjob/examples/mr_spark_nick_nack_word_count.py
- mrjob/hadoop.py
- mrjob/runner.py
- tests/test_emr.py
- tests/test_hadoop.py
- tests/test_runner.py
This adds libjars support to Spark (fixes #1469) and also adds some missing libjars and jobconf support to JAR steps (fixes #1481).
Still need to hand-test this.
> Spark libjars

- mrjob/emr.py
- mrjob/examples/mr_sparkaboom.py
- mrjob/hadoop.py
- mrjob/logs/mixin.py
- mrjob/logs/task.py
- tests/logs/test_mixin.py
- tests/logs/test_task.py
- tests/test_emr.py
- tests/test_hadoop.py
This updates our log-interpreting code to correctly handle logs from Spark (fixes #1378)
Highlights:
* correct filenames (the primary Spark task log is named `stderr`, not `syslog`)
* don't try to fetch counters from Spark
* different sorting and logic for which Spark logs to parse (we only look at `stdout` if the `stderr` file indicates that the application exited)
* many methods, including those in `LogInterpretationMixin`, now take `step_type` as a required argument
> Spark log interpretation

- docs/guides/emr-opts.rst
- mrjob/emr.py
- tests/mockboto.py
- tests/test_emr.py
Bump the default AMI version to 4.8.2, because 3.11.0 has iffy Spark support (no Python 3, doesn't properly detect errors).
Fixes #1486
> bump default AMI version to 4.8.2

- mrjob/emr.py
- mrjob/runner.py
- tests/test_emr.py
Warn that "loose" protocols are going away (fixes #1452).
Issue a warning about running Spark on 3.x AMI versions even if we're not trying to run Python 3 (see #1485).
> Misc warnings

- docs/guides/configs-hadoopy-runners.rst
- mrjob/hadoop.py
- mrjob/options.py
- tests/test_emr.py
- tests/test_hadoop.py
Added a `spark_master` option to the Hadoop runner (fixes #1484)
Also warns if you're trying to use archives with a non-YARN spark master, since Spark will probably ignore these.
> spark_master option

- docs/guides/configs-all-runners.rst
- mrjob/dataproc.py
- mrjob/emr.py
- mrjob/options.py
- mrjob/runner.py
- mrjob/tools/emr/create_cluster.py
- mrjob/util.py
- tests/logs/test_task.py
- tests/mockboto.py
- tests/mockgoogleapiclient.py
- tests/test_dataproc.py
- tests/test_emr.py
- tests/test_hadoop.py
- tests/test_runner.py
This uses a `.zip` file rather than a tarball to bootstrap mrjob, for better compatibility with Spark. Fixes #1492.
> bootstrap mrjob with .zip, not .tar.gz

- mrjob/runner.py
- tests/test_hadoop.py
- tests/test_runner.py
In the Hadoop runner, we now add the mrjob zip to `py_files`. This is keyed off `BOOTSTRAP_MRJOB_IN_SETUP`, so in theory this would happen in the local runners as well if they supported Spark.
Fixes #1496.
> bootstrap mrjob in Spark

- mrjob/logs/errors.py
- mrjob/logs/history.py
- mrjob/logs/ids.py
- tests/logs/test_errors.py
- tests/logs/test_history.py
We don't need it to sort by recency, and you can infer attempt number directly from container ID anyway. Fixes #1487.
> drop container_to_attempt_id

- mrjob/emr.py
- mrjob/logs/wrap.py
- tests/logs/test_wrap.py
- tests/test_emr.py
This change gracefully handles the errors we get when there is no `ssh` binary, or when `ssh_bin` is misconfigured. Fixes #1474.
> Handle missing SSH binary

- mrjob/tools/emr/terminate_idle_clusters.py
- tests/tools/emr/test_terminate_idle_clusters.py
This removes a special case from the `terminate-idle-clusters` that was designed to leave Hive clusters alone (see #60). Instead, if EMR says a cluster is idle, we believe it. Fixes #1363.
If this script *does* terminate interactive Hadoop processes that aren't really idle, the workaround is to run all your ordinary mrjobs with a particular pool name, and then specify that pool name to `terminate-idle-clusters`. Alternatively, you could just set `max_hours_idle` and let the clusters terminate themselves.
> simplify terminate-idle-clusters

- CHANGES.txt
- mrjob/dataproc.py
- mrjob/emr.py
- mrjob/examples/mr_spark_nick_nack_word_count.py
- tests/test_dataproc.py
- tests/test_emr.py
- tests/test_runner.py
This includes `python_bin` in the pool hash whenever mrjob is bootstrapped. This fixes an issue where a job can join a pool started by a different Python version, and not be able to access the `mrjob` library (since it was installed for a different version of Python). Fixes #1503.
Also a couple of other small fixes:
* the "compileall" step of the master bootstrap script now uses the `-q` option, which suppresses everything except errors, making it easier to debug issues with development versions of the mrjob library (e.g. files that only compile in other versions of Python)
* made sure that the master bootstrap script is always created when using pooling, since the pool name and hash are passed as arguments to it.
> make pooling python-bin aware, other fixes

- CHANGES.txt
- README.rst
- docs/guides.rst
- docs/guides/configs-all-runners.rst
- docs/guides/configs-hadoopy-runners.rst
- docs/guides/emr-opts.rst
- docs/guides/runners.rst
- docs/guides/setup-cookbook.rst
- docs/guides/spark.rst
- docs/guides/writing-mrjobs.rst
- docs/index.rst
This updates the documentation for Spark. Also updated the setup cookbook to prefer `py_files` over a setup script.
Also merges the speculative 0.5.8.spark release into 0.5.7 in `CHANGES.txt` and documentation.
> Spark docs

- CHANGES.txt
- docs/guides/configs-all-runners.rst
- docs/guides/setup-cookbook.rst
- mrjob/options.py
- mrjob/runner.py
- mrjob/setup.py
- mrjob/util.py
- tests/mr_os_walk_job.py
- tests/sandbox.py
- tests/test_runner.py
- tests/test_setup.py
You can now pass directories to mrjob with the `--dir` switch, the `upload_dirs` option, or by using the syntax ``dir/#`` in setup scripts. Fixes #23.
> auto-archive directories

- .travis.yml
- setup.py
This acknowledges that mrjob works with Python 3.6 (newly released) and adds a continuous integration test builder for 3.6. Fixes #1507.
> Add Python 3.6 to .travis.yml and classifiers

- CHANGES.txt
- mrjob/emr.py
- mrjob/fs/ssh.py
- mrjob/tools/emr/mrboss.py
- tests/mockboto.py
- tests/test_emr.py
- tests/tools/emr/test_mrboss.py
When we fetch task logs via SSH, we have to tunnel through the master node to the worker (core and task) nodes. Previously, we relied on running `dfsadmin`, which excludes task nodes because they don't run HDFS.
This change includes task nodes as well (fixes #1400) by using the `ListInstances` EMR API call (fixes #1345).
> use ListInstances, not dfsadmin

- docs/guides/configs-all-runners.rst
- mrjob/dataproc.py
- mrjob/emr.py
- mrjob/hadoop.py
- mrjob/launch.py
- mrjob/options.py
- mrjob/runner.py
- mrjob/sim.py
- tests/test_hadoop.py
- tests/test_launch.py
- tests/test_runner.py
This allows you to specify where to put the intermediate output of multi-step jobs (e.g. on S3, for future safekeeping). We don't want to do this by default (HDFS is faster), but this can be useful for debugging.
Fixes #263.
> add --step-output-dir option

- mrjob/step.py
- tests/test_job.py
- tests/test_step.py
This adds `jobconf` to all step types and adds type-checking of most keyword arguments. Fixes #1447.
This also replaces a lot of boilerplate code with a common base class (`_Step`), fixing #1368. Left `MRStep` alone because it is so old and different (see #1518).
> add jobconf for all step types

- mrjob/runner.py
- mrjob/util.py
- tests/test_emr.py
- tests/test_hadoop.py
This uses whatever the `sh_bin` option is set to for wrapping streaming tasks that require piping one command into another. That way, if you don't have `bash` installed, no worries.
> use sh_bin, not bash_wrap()

- CHANGES.txt
- docs/utils-cat.rst
- mrjob/cat.py
- mrjob/examples/mr_grep_word_freq_count.py
- mrjob/examples/mr_u_word_freq_count.py
- mrjob/job.py
- mrjob/local.py
- mrjob/util.py
- tests/test_job.py
- tests/test_local.py
Made several important fixes to local mode and pre-filters:
#1061: Local mode can now handle compressed input files passed through pre-filters. Every file that local mode pipes into another command first goes through `mrjob/cat.py`, which auto-decompresses compressed files based on their file extension. `mrjob/cat.py` depends on the standard library only, so we don't need to hack `PYTHONPATH` to ensure access to `mrjob`
#1126: This was a symptom of general brokenness with pre-filters, and should be fixed.
#1521: You can now override `*_pre_filter()` methods to get pre-filters in a single-step job. This used be totally broken.
#1524: Local mode used to report a failure if the pre-filter command reported failure. This can be a problem; for example BSD grep reports exit status 1 on no …
> A ton of local mode/pre-filter fixes

- CHANGES.txt
- mrjob/util.py
- tests/test_util.py
Re-implement `parse_and_save_options()` with about a quarter of the code, and deprecate a bunch of other option-parsing util functions that are no longer used. Fixes #1458
> simplify opt parsing

- CHANGES.txt
- mrjob/job.py
- mrjob/launch.py
- mrjob/options.py
- mrjob/util.py
- tests/test_job.py
This replaces the extremely spammy `--help` printout with three possible modes:
* basic help (`--help`), which shows config, input/output, and verbosity options, plus any custom options
* runner help (`--help -r <runner>`) which shows runner-specific options for one runner
* steps help (`--help --steps`) which show the options that select which part of a job to run (rarely needed)
To show deprecated switches, you have to add the `--deprecated` option.
Also added deprecation warnings for opt groups and the `get_all_opt_groups()` method. Also deprecated the `--strict-protocols` switch (which will go away in v0.6.0 because it'll be irrelevant.
> improve help, deprecate opt groups

- mrjob/local.py
- tests/test_inline.py
- tests/test_local.py
Local mode now uploads mrjob/cat.py (which handles uncompressing input files, to pipe them into the task) into the job's working directory and invokes them by relative path. This allows you to use a specially designed Docker script as your python_bin, since now all the files you need to get into Docker will be in the job's working dir.
Also removed some uneccessary `PYTHONPATH` code from the local runner that only existed to support an earlier, unreleased version of `cat.py`.
> use relative path to invoke cat.py in local mode

- mrjob/emr.py
- tests/test_emr.py
Start a new SSH tunnel when we run our job on a different cluster (which can happen due to pooling auto-recovery). Fixes #1549.
> relaunch SSH tunnel when connecting to new cluster

- mrjob/emr.py
- tests/test_emr.py
mrjob can now get job progress whether or not you have a working SSH tunnel, as long as you can SSH into the master node. Fixes #1547
> SSH tunnel job progress fallback

- CHANGES.txt
- docs/runners-emr.rst
- mrjob/aws.py
- mrjob/emr.py
- mrjob/fs/s3.py
- mrjob/retry.py
- mrjob/tools/emr/s3_tmpwatch.py
- mrjob/tools/emr/terminate_idle_clusters.py
- mrjob/util.py
- setup.py
- tests/fs/test_s3.py
- tests/mockboto.py
- tests/test_emr.py
- tests/test_runner.py
- tests/tools/emr/test_s3_tmpwatch.py
- tests/tools/emr/test_terminate_idle_clusters.py
mrjob now uses `boto3` for all of its S3 needs. This fixes the S3 part of #1304 (only EMR left).
> port S3 code from boto to boto3

- mrjob/emr.py
- mrjob/tools/emr/s3_tmpwatch.py
- tests/mockboto.py
- tests/test_emr.py
- tests/tools/emr/test_s3_tmpwatch.py
- tests/tools/emr/test_terminate_idle_clusters.py
Turns out if you want to interact with `boto3` `datetime`s, you need to specify a timezone. This updates `boto3` code (everything having to do with S3 and IAM) to specify `dateutil.tz.tzutc()` as the time zone.
`dateutil` is a dependency of `boto3`. Might want to add it explicitly.
> boto3 tzutc() fix

- mrjob/cat.py
- tests/mockboto.py
Turns out `boto3`'s `StreamingBody` isn't *really* a fileobj. This fixes the way we deal with `StreamingBody` so that we can `cat()` data from S3 again.
> boto3 StreamingBody fix

- mrjob/dataproc.py
- mrjob/emr.py
- tests/test_emr.py
- tests/test_local.py
This fixes an edge case that can happen when mrjob is already installed and then we try to unzip our bootstrapped mrjob in the same directory, causing `unzip` to go into interactive mode and wait forever. Fixes #1567.
Also fixed the file extension of the master bootstrap script (fixes #1504).
This affects both Dataproc and EMR (which probably should share common code).
> fix unzip stall when bootstrapping mrjob

- docs/guides/writing-mrjobs.rst
- docs/protocols.rst
- mrjob/protocol.py
- setup.py
- tests/test_protocol.py
mrjob will now use `rapidjson` by default if it's installed and `ujson` isn't available. Fixes #1579.
> Add support for rapidjson

- docs/guides/emr-opts.rst
- mrjob.conf.example
- mrjob/emr.py
- mrjob/options.py
- mrjob/protocol.py
- mrjob/setup.py
- tests/test_emr.py
- tests/test_launch.py
- tests/test_option_store.py
- tests/test_protocol.py
Rename this to `aws_security_token` so we can get rid of the old, deprecated name in mrjob 0.6.
> aws_session_token option rename

- docs/guides/py2-vs-py3.rst
- mrjob/fs/hadoop.py
- mrjob/hadoop.py
- mrjob/logs/step.py
- mrjob/logs/wrap.py
- mrjob/parse.py
- mrjob/py2.py
- mrjob/ssh.py
- mrjob/tools/emr/mrboss.py
- tests/test_py2.py
This makes Python 2 act a bit more like Python 3, and ensures that we don't get encoding errors when trying to log non-UTF-8 bytes in Python 2 (fixes #1585).
This also fixes a specific logging issue having to do with bootstrap errors (fixes #1580).
> replace to_string() with to_unicode()

- docs/guides/emr-advanced.rst
- docs/guides/emr-bootstrap-cookbook.rst
- docs/guides/emr-opts.rst
- docs/guides/emr.rst
- docs/guides/pooling.rst
- docs/whats-new.rst
- mrjob/emr.py
- mrjob/options.py
- tests/test_emr.py
This change ensures that pooling is turned on by default, and that any cluster started by mrjob will eventually self-terminate when idle (either because of our bootstrap script or because pooling is turned off). Fixes #1531.
Also deprecated `visible_to_all_users` (fixes #1598).
> always auto-terminate

- mrjob/cat.py
- mrjob/fs/base.py
- mrjob/fs/gcs.py
- mrjob/fs/hadoop.py
- mrjob/fs/local.py
- mrjob/fs/s3.py
- mrjob/runner.py
- mrjob/util.py
- tests/fs/test_base.py
- tests/fs/test_gcs.py
- tests/fs/test_hadoop.py
- tests/fs/test_local.py
- tests/fs/test_s3.py
- tests/test_util.py
This makes the `cat()` method in filesystems yield chunks of bytes, which may or may not correspond to lines. Fixes #1533.
Didn't touch the SSH FS because it lacks tests and needs to be rewritten not to dump file contents to memory (see #1544).
> cat byte chunks, not lines

- docs/guides/py2-vs-py3.rst
- docs/guides/runners.rst
- docs/guides/testing.rst
- docs/runners-runner.rst
- mrjob/job.py
- mrjob/launch.py
- mrjob/runner.py
- tests/job.py
- tests/test_dataproc.py
- tests/test_emr.py
- tests/test_hadoop.py
- tests/test_inline.py
- tests/test_job.py
- tests/test_launch.py
- tests/test_local.py
- tests/test_runner.py
This creates a new way of parsing job output that doesn't rely on output files being line-based. Fixes #1604.
> add cat_output()/parse_output(), deprecate old way of parsing job output

- mrjob/parse.py
- tests/fs/test_hadoop.py
- tests/fs/test_s3.py
- tests/mockhadoop.py
- tests/test_hadoop.py
- tests/test_parse.py
More a cosmetic than functional change since `boto` is handling under the hood, but sometimes my jobs fail on the `ValueError` when I copy/paste `s3a` uris into input configuration. Since `s3n` is deprecated it makes sense to just support all the protocol prefixes.
> Accept input paths with an s3a prefix

- CHANGES.txt
- mrjob/cat.py
`mrjob.cat` was a temporary shim to pass decompressed input to binaries run in local mode, which we don't need now that the sim runner has been refactored.
> cat.py doesn't need to be executable

- docs/guides/emr-opts.rst
- docs/guides/pooling.rst
- mrjob/emr.py
- mrjob/options.py
- tests/mock_boto3/emr.py
- tests/test_emr.py
- tests/tools/emr/test_create_cluster.py
Added an `instance_groups` option, which allows for EBS volume configuration (fixes #1357). Pooling understands instance groups.
Also fixed the way pooling deals with un-requested instance roles on a pooled cluster (see #1630).
> instance_groups option

- mrjob/tools/emr/report_long_jobs.py
- tests/tools/emr/test_report_long_jobs.py
Add a feature to report_long_jobs to exclude clusters with specific tags.
Internal ticket MRJOB-169
> Support for --exclude tags in report_long_jobs

- docs/guides/emr-opts.rst
- docs/guides/pooling.rst
- mrjob/emr.py
- mrjob/options.py
- mrjob/pool.py
- setup.py
- tests/mock_boto3/emr.py
- tests/test_emr.py
- tests/tools/emr/test_create_cluster.py
This adds the `instance_fleets` option and reasonable pooling rules for instance fleets. (fixes #1569). Also adds the `--subnets` command-line option and allows the `subnet` opt to be a list.
This also moves a fair amount of pooling code from `mrjob/emr.py` (which is huge) to `mrjob/pool.py`.
> Instance fleets, including pooling

- mrjob/emr.py
- mrjob/retry.py
- tests/test_emr.py
Currently spark support warnings and pooling can potentially error out if trying to inspect a cluster that uses instance fleets. This change allows us to safely ignore instance fleet clusters. Fixes #1639.
> ignore instance fleets (v0.5.x)

- CHANGES.txt
- docs/job.rst
- docs/whats-new.rst
- mrjob/inline.py
- mrjob/job.py
- mrjob/launch.py
- mrjob/options.py
- mrjob/tools/emr/audit_usage.py
- mrjob/tools/emr/create_cluster.py
- mrjob/tools/emr/mrboss.py
- mrjob/tools/emr/report_long_jobs.py
- mrjob/tools/emr/s3_tmpwatch.py
- mrjob/tools/emr/terminate_cluster.py
- mrjob/tools/emr/terminate_idle_clusters.py
- mrjob/util.py
- tests/test_bin.py
- tests/test_emr.py
- tests/test_hadoop.py
- tests/test_job.py
- tests/test_launch.py
- tests/tools/emr/test_terminate_cluster.py
MRJob now uses `argparse` instead of `optparse` (fixes #1587). `MRJobLauncher` methods have been renamed to reflect this (for example `configure_args()` not `configure_options()`). The old methods are still around as shims.
Kept the attribute `MRJobLauncher.options`, both because it means less to update, and because `argparse`'s naming conventions don't distinguish well between command-line arguments and parsed arguments (they're both "args"). Because `argparse` handles position arguments as well, `MRJobLauncher.args` is now a deprecated shim for `MRJobLauncher.options.args` (they're still just called "args" because they can be either input files or an input and output URI passed to spark jobs, depending on context).
There's still some work to do in terms of updating tests and examples …
> use argparse instead of optparse

- docs/guides/emr-opts.rst
- mrjob/cloud.py
- mrjob/dataproc.py
- mrjob/emr.py
- mrjob/fs/gcs.py
- mrjob/launch.py
- mrjob/options.py
- tests/mock_boto3/emr.py
- tests/test_dataproc.py
- tests/test_emr.py
- tests/tools/emr/test_create_cluster.py
This replaces `emr_api_params`, which was tied to `boto` 2 and is unusable, with `extra_cluster_params`, which speaks JSON and works on Dataproc as well as EMR. Fixes #1574.
> added extra_cluster_params, disabled emr_api_params

- mrjob/cat.py
- mrjob/job.py
- mrjob/sim.py
- mrjob/util.py
- tests/test_local.py
- tests/test_util.py
Fixes #1605, #1609.
Also removed `open_input()`, which never appeared in a release and was only used by the sim runner.
> deprecate read_file(), read_input()

- mrjob/dataproc.py
- mrjob/emr.py
- mrjob/hadoop.py
- mrjob/launch.py
- mrjob/runner.py
- mrjob/sim.py
- tests/test_emr.py
- tests/test_runner.py
`check_input_paths` now automatically works the same for all runners, running before `_run()`. Fixes #1614.
> simplify check_input_paths

- docs/guides/configs-reference.rst
- docs/guides/setup-cookbook.rst
- docs/guides/writing-mrjobs.rst
- mrjob/examples/contrib/mr_pegasos_svm.py
- mrjob/examples/mr_grep.py
- mrjob/examples/mr_log_sampler.py
- mrjob/examples/mr_page_rank.py
- mrjob/examples/mr_postfix_bounce/mr_postfix_bounce.py
- mrjob/examples/mr_text_classifier.py
- mrjob/launch.py
- mrjob/tools/emr/terminate_idle_clusters.py
- tests/mr_cmd_job.py
- tests/mr_filter_job.py
- tests/mr_jar_and_streaming.py
- tests/mr_just_a_jar.py
- tests/mr_null_spark.py
- tests/mr_runner.py
- tests/mr_spark_jar.py
- tests/mr_spark_script.py
- tests/mr_tower_of_powers.py
- tests/test_inline.py
- tests/test_launch.py
Updated all the docs, examples, and tests that still rely on the old optparse hooks. Added an explicit test to make sure they all work, and caught at least one bug (with the `args` deprecated property). Fixes #1645.
> update code using deprecated optparse hooks

- mrjob/launch.py
- mrjob/runner.py
- tests/test_launch.py
- tests/test_runner.py
This makes the `extra_args` init keyword to `MRJobRunner` do the work of `file_upload_args`, using path dicts. Fixes #1656.
> deprecate file_upload_args

- docs/guides/concepts.rst
The original text was:
"The master The master is responsible for scheduling..."
Updated to:
"The master is responsible for scheduling..."
The diff gets all wonky, b/c I fixed the surrounding text to match the column-width formatting of the rest of the doc.
> Fixing small typo in "concepts" guide

- mrjob/util.py
I had to read this like 8 times before I figured out what was going on. Figured I'd save the next person some confusion.
> `log_to_stream` docstring typo fix

- docs/guides/configs-reference.rst
- docs/guides/emr-opts.rst
- mrjob/emr.py
- tests/test_emr.py
Fixes #1637.
For instance, you can now set instance configs on the command line if `instance_fleets` is specified in your config files.
> fix and document precedence of various instance options

- mrjob/hadoop.py
- mrjob/local.py
- mrjob/runner.py
- mrjob/ssh.py
- tests/fs/test_ssh.py
- tests/mockboto.py
- tests/mockgoogleapiclient.py
- tests/mockssh.py
- tests/test_hadoop.py
Makes some changes to the test framework that make it possible for some Windows tests to run.
Was hoping to fix the tests on v0.5.x first and then on v0.6.0, but that'll be too time-consuming. Instead will focus on v0.6.0, and backport windows-related fixes.
> start fixing windows tests

- mrjob/sim.py
- tests/test_local.py
This fixes #1649, an issue someone was having in Python 3 on Windows.
> fall back to copying when os.symlink() fails

- docs/guides/emr-opts.rst
- docs/guides/pooling.rst
- mrjob/cloud.py
- mrjob/dataproc.py
- mrjob/emr.py
- mrjob/options.py
- mrjob/tools/emr/terminate_idle_clusters.py
- tests/test_dataproc.py
- tests/test_emr.py
- tests/test_emr_pooling.py
- tests/test_pool.py
- tests/tools/emr/test_create_cluster.py
- tests/tools/emr/test_terminate_idle_clusters.py
Pooling is no longer on by default (fixes #1663).
EMR no longer bills by the hour, so disabled `mins_to_end_of_hour` (#1687) and changed `max_hours_idle` to `max_mins_idle` (#1686).
> Turn off pooling by default

- docs/guides/writing-mrjobs.rst
- mrjob/examples/contrib/mr_pegasos_svm.py
- mrjob/examples/mr_grep.py
- mrjob/examples/mr_log_sampler.py
- mrjob/examples/mr_page_rank.py
- mrjob/examples/mr_text_classifier.py
- mrjob/options.py
- mrjob/tools/emr/audit_usage.py
- mrjob/tools/emr/create_cluster.py
- mrjob/tools/emr/mrboss.py
- mrjob/tools/emr/report_long_jobs.py
- mrjob/tools/emr/s3_tmpwatch.py
- mrjob/tools/emr/terminate_cluster.py
- mrjob/tools/emr/terminate_idle_clusters.py
- tests/test_launch.py
Refresh the docstrings for mrjob subcommands (fixes #1646).
Also updated alphabetization of switches for argparse, and made a small fix for optparse option emulation (fixes #1691)
> update mrjob command docstrings for v0.6.0

- mrjob/parse.py
Update parse.py to the 0.6.0 version to allow using s3a while retaining the 0.5.X style configurations
> Update parse.py to support s3a

- mrjob/emr.py
- mrjob/fs/s3.py
- mrjob/logs/errors.py
- mrjob/logs/history.py
- mrjob/logs/ids.py
- mrjob/logs/mixin.py
- mrjob/logs/task.py
- mrjob/logs/wrap.py
- tests/logs/test_errors.py
- tests/logs/test_history.py
- tests/logs/test_mixin.py
- tests/logs/test_task.py
- tests/logs/test_wrap.py
- tests/mock_boto3/s3.py
- tests/test_emr.py
Rather than checking every task log until we find an error (which can take a lot of time depending on how many tasks there are and how sparse errors are), we rely on the step and history logs to tell us which tasks had errors, and only check the corresponding task logs. This is faster and also more accurate, as it avoids finding "errors" in tasks that Hadoop terminated voluntarily. Fixes #1706.
There is unfortunately no way to get around reading the history file (on YARN, anyhow), as it is the only place where we can find the mapping from attempt ID (which errors are identified by) to container ID (which is the way task logs are organized).
> quicker task log picking

- CHANGES.txt
- mrjob/dataproc.py
- mrjob/fs/gcs.py
- mrjob/fs/s3.py
- setup.py
- tests/fs/test_gcs.py
- tests/mock_boto3/s3.py
- tests/mock_google/__init__.py
- tests/mock_google/case.py
- tests/mock_google/storage.py
- tests/mockgoogleapiclient.py
- tests/test_dataproc.py
Ported our Google Cloud Storage code from the old `google-api-python-client` library to the new `google-cloud` one (part of #1730).
Still to do:
* port Google Cloud Dataproc code
* provide a way to specify credentials file through options
> Port GCS code from google-api-python-client to google-cloud-sdk

- mrjob/tools/emr/terminate_idle_clusters.py
`mrjob terminate-idle-clusters` script now only looks at `WAITING` and `RUNNING` clusters, saving API calls.  Fixes #1722.
For why we look at `RUNNING` clusters, see #365. No idea if this is still a live issue (it was first addressed in 2012), but the main efficiency boost is to avoid looking at the vast majority of clusters that are already terminated.
> more efficient terminate-idle-clusters

- docs/guides/emr-opts.rst
- mrjob/bootstrap/terminate_idle_cluster_dataproc.sh
- mrjob/bootstrap/terminate_idle_cluster_emr.sh
- mrjob/cloud.py
- mrjob/emr.py
- tests/test_emr.py
The idle termination script (on both EMR and Dataproc) now waits 10 minutes after launching before terminating the cluster, to avoid race conditions where the first job never gets a chance to run. Fixes #1694.
> Idle grace period

- docs/guides/dataproc-quickstart.rst
- mrjob/dataproc.py
- tests/mock_google/case.py
- tests/test_dataproc.py
This brings the Dataproc Quickstart up to date (fixes #1589).
Also added a small tweak to the way we load credentials, so it's possible to use mrjob with Dataproc without installing `gcloud` (fixes #1742).
> Dataproc Quickstart

- docs/guides/configs-all-runners.rst
- docs/guides/dataproc-quickstart.rst
- docs/guides/emr-quickstart.rst
- mrjob/launch.py
- mrjob/options.py
- tests/test_job.py
- tests/test_launch.py
If you specify ``--output-dir``, this automatically turns off catting output to stdout (fixes #1739). You can still set it manually with ``--cat-output`` and ``--no-cat-output`` (``--no-output`` exists as an alias for ``--no-cat-output``).
> --output-dir implies --no-cat-output

- mrjob/cloud.py
- mrjob/dataproc.py
- mrjob/emr.py
- mrjob/options.py
- tests/test_dataproc.py
- tests/test_emr.py
This enables the `--ssh-tunnel` option on Dataproc, allowing you to track the process of your job through a web browser. Fixes #1670.
Also moved some common code with EMR into `mrjob/cloud.py` and added a workaround an unrelated race condition having to do with parsing job driver output.
> SSH tunnel on Dataproc

- mrjob/cloud.py
- mrjob/dataproc.py
- mrjob/emr.py
- mrjob/fs/gcs.py
- tests/mock_google/storage.py
- tests/test_dataproc.py
Enabled the `cloud_upload_part_size` option on the dataproc runner, which is used to set `chunk_size` when uploading. Fixes #1404
> chunked uploading on dataproc runner

- mrjob/dataproc.py
- mrjob/fs/gcs.py
- setup.py
- tests/mock_google/case.py
- tests/mock_google/storage.py
Removes shim code backported from the development version `google-cloud-storage` in favor of using `google-cloud-storage` 1.9.0 directly.
> require google-cloud-storage>=1.9.0

- docs/guides/dataproc-opts.rst
- mrjob/dataproc.py
- mrjob/options.py
- tests/mock_google/dataproc.py
- tests/test_dataproc.py
- tests/tools/emr/test_create_cluster.py
Added `*_instance_configs` opts to the Dataproc runner. Fixes #1681.
> Dataproc instance configs

- docs/guides/dataproc-opts.rst
- mrjob/dataproc.py
- mrjob/options.py
- tests/mock_google/dataproc.py
- tests/test_dataproc.py
- tests/tools/emr/test_create_cluster.py
Added `*_instance_configs` opts to the Dataproc runner. Fixes #1681.
> Dataproc instance config opts

- docs/guides/dataproc-opts.rst
- mrjob/dataproc.py
- mrjob/options.py
- tests/mock_google/dataproc.py
- tests/sandbox.py
- tests/test_dataproc.py
This adds the ``service_account`` and ``service_account_scopes`` opts to the Dataproc runner. Fixes #1682.
> Dataproc service account opts

- docs/guides/dataproc-opts.rst
- mrjob/dataproc.py
- mrjob/options.py
- tests/mock_google/dataproc.py
- tests/test_dataproc.py
Added the `cluster_properties` opt to Dataproc, which allows us to set up the config files for Hadoop etc. on the cluster. Fixes #1680.
> cluster_properties opt

- docs/guides/dataproc-opts.rst
- mrjob/dataproc.py
- mrjob/emr.py
- mrjob/options.py
- mrjob/runner.py
- tests/mock_google/dataproc.py
- tests/test_dataproc.py
Added `network` and `subnet` opts to Dataproc. Fixes #1683.
> Dataproc network and subnet opts

- docs/guides/setup-cookbook.rst
- docs/guides/writing-mrjobs.rst
- docs/job.rst
Added mapper_raw() to docs (fixes #1753).
Also removed an obsolete reference to `bash_wrap()`, which no longer exists (fixes #1783).
> document mapper_raw()

- mrjob/examples/mr_jar_step_example.py
- mrjob/logs/step.py
- tests/logs/test_step.py
mrjob now gives a clear error message when you specify an invalid jar on Dataproc or your own Hadoop cluster.
(EMR fails in the controller on an invalid JAR path, so a different strategy is needed. See #1786.)
> handle "Not a valid JAR" error message

- mrjob/retry.py
according to the comment the retry wrapper wants to change its function \_\_name\_\_ to the original function name but uses "==".
Also the brackets some lines above are not needed.
> set function name instead of comparing it

- docs/guides/dataproc-opts.rst
- mrjob/dataproc.py
- mrjob/options.py
- tests/mock_google/dataproc.py
- tests/test_dataproc.py
Now that we're using the built-in idle timeout feature on Dataproc, we don't really need to worry about what scopes the user is using.
This change removes the default value for `service_account_scopes`, instead just letting the API use its own default. It also removes the append semantics for configuring this option, since the main point is to limit the scope of an existing account.
> rework google_account_scopes

- .travis.yml
- CHANGES.txt
- README.rst
- docs/index.rst
- setup.py
Python 3.3 reached end of life last September, and stopped working on Travis CI within the last week. This makes it official that mrjob no longer supports Python 3.3.
> Drop python 3.3

- mrjob/tools/emr/terminate_idle_clusters.py
- tests/tools/emr/test_terminate_idle_clusters.py
If there is a cluster with Termination Protection enabled, and this batch attempts to terminate it, the batch fails with ValidationError and cannot continue to the next cluster.
This patch assumes that Termination Protection is enabled on purpose, and skips clusters which have it enabled, allowing the rest of the clusters in the account to be checked and terminated.
I also have a backport for v0.5.x, which would be super helpful to have released.
> Respect termination protection to avoid boto ValidationError

- mrjob/tools/emr/terminate_idle_clusters.py
- tests/mockboto.py
- tests/tools/emr/test_terminate_idle_clusters.py
This backports #1801 for v0.5.x. It does it slightly differently, since I can't find a `TerminationProtected` attribute ever returned by boto. So rather than checking for termination protection ahead of time, we catch the ValidationError and check if it mentions termination protection - it's a bit hacky.
> v0.5.x backport of Termination Protected bugfix

- docs/guides/emr-opts.rst
- mrjob/emr.py
- tests/test_emr.py
The `mins_to_end_of_hour` option no longer makes since Amazon stopped billing by the full hour.
This pull request disables `mins_to_end_of_hour` in a minimally invasive way, by setting its default value to 60.
> disable mins_to_end_hour by default

- docs/_templates/indexsidebar.html
- docs/guides/cloud-opts.rst
- docs/guides/emr-opts.rst
- mrjob/cloud.py
- mrjob/dataproc.py
- mrjob/emr.py
- mrjob/examples/mr_phone_to_url.py
- mrjob/options.py
- tests/mock_boto3/emr.py
- tests/test_emr.py
- tests/test_emr_pooling.py
- tests/tools/emr/test_create_cluster.py
This allows launching clusters with custom machine images on EMR (fixes #1805).
Added this as a "cloud runner" option, with the intent of adding Dataproc support later (see #1820). This is something that I imagine would be a standard feature on any Hadoop-as-a-service.
> add image_id option

- mrjob/bootstrap/terminate_idle_cluster_emr.sh
- mrjob/emr.py
- tests/mock_boto3/emr.py
- tests/test_emr_pooling.py
Updated the master bootstrap script to continue after issuing a `shutdown -h now`. There were apparently some cases where shutdown was issued and nothing happened; hopefully even if the box doesn't shut down the first time the script asks, it'll shut down on the second or third try. Fixes #1819.
As part of diagnosing this issue, updated the idle self-termination script on EMR so that it logs what it's doing to `/var/log/bootstrap-actions/mrjob-idle-termination.log`. This seems like it could only be useful, so leaving it in.
Also updated mock_boto3 to better match the error messages we get when a cluster self-terminates, and in the process found and fixed a bug (#1822) affecting single-node clusters.
> idle self-termination improvements

- CHANGES.txt
- mrjob/emr.py
- tests/mock_boto3/emr.py
- tests/test_emr.py
> bump default AMI to 5.16.0

- mrjob/fs/s3.py
- tests/fs/test_s3.py
This adds certain SSLErrors to the list of exceptions that we catch (fixes #1827).
Also added automated tests for `_wrap_aws_client()`.
> catch SSL timeouts

- mrjob/emr.py
- mrjob/runner.py
- tests/test_emr.py
This automatically adds the `__mrjob_label` and `__mrjob_owner` tags to clusters created by mrjob, for use by CloudWatch etc. Fixes #1828.
> tag clusters with label and owner

- docs/guides/cloud-opts.rst
- docs/guides/emr-opts.rst
- mrjob/emr.py
- mrjob/fs/s3.py
- mrjob/retry.py
- tests/fs/test_s3.py
- tests/sandbox.py
- tests/test_emr.py
When the EMR client encounters a transient error, it will now back off at least at long as `check_cluster_every`. Fixes #1799.
> min backoff for EMR client

- docs/guides/configs-hadoopy-runners.rst
- mrjob/options.py
- tests/test_bin.py
- tests/test_dataproc.py
- tests/test_emr.py
- tests/test_hadoop.py
- tests/test_job.py
- tests/test_local.py
- tests/test_sim.py
Hadoop has worked this way for ages, and mrjob should match. Fixes #1839.
> -D as synonym for --jobconf

- mrjob/bin.py
- mrjob/cloud.py
- mrjob/emr.py
- mrjob/runner.py
- tests/test_bin.py
- tests/test_hadoop.py
This treats bootstrapping mrjob the same way in Hadoop Streaming as it does in Spark, by creating a .zip file of mrjob, and adding it to py_files (fixes #1842).
This undoes a decision to patch `py_files` into `setup`, instead explicitly handling them as part of setup wrapper creation.
> bootstrap mrjob in py_files, not setup

- mrjob/bin.py
- mrjob/conf.py
- mrjob/job.py
- mrjob/launch.py
- mrjob/options.py
- mrjob/runner.py
- tests/test_bin.py
- tests/test_conf.py
- tests/test_job.py
- tests/test_runner.py
You can now set `jobconf: mapred.whatever: true` in your conf file, and Hadoop will be passed `-D mapred.whatever=true`, rather than `-D mapred.whatever=True`. Fixes #323. The `jobconf` option now uses custom combiner (`combine_jobconfs()`), so runners can now expect that `self._opts['jobconf']`'s values are all strings.
This also allowed us to remove some fairly flawed code that was trying to do this from `MRJob.jobconf()`. `MRJob.jobconf()` and `MRJob.libjars()` are no longer responsible for handling command line options, leaving that to `MRJobLauncher` instead, fixing #1453.
> fix booleans in jobconf, simplify jobconf() and libjars()

- mrjob/launch.py
- mrjob/options.py
- tests/test_launch.py
`add_file_arg()` now correctly accepts `type=str` (it had some old code from `add_file_option()` that incorrectly expected `'string'`). Fixes #1858.
`add_passthrough_option()` and related optparse emulation code now handles the undocumented type `'str'`, which is an alias for `'string'`. Fixes #1857.
> argument parser fixes

- docs/guides/configs-hadoopy-runners.rst
- mrjob/options.py
- tests/test_bin.py
- tests/test_hadoop.py
This deprecates the annoying-to-use `--spark-arg` and `--hadoop-arg` switches in favor of `--spark-args` and `--hadoop-args`, which can take a string containing several arguments, separated by spaces. Fixes #1844.
> --spark-args and --hadoop-args switches

- docs/guides/configs-hadoopy-runners.rst
- mrjob/bin.py
- mrjob/emr.py
- mrjob/hadoop.py
- mrjob/job.py
- mrjob/options.py
- mrjob/runner.py
- mrjob/tools/diagnose.py
- tests/test_bin.py
- tests/test_emr.py
- tests/test_hadoop.py
The Hadoop runner now uploads `py_files` to HDFS when running on Spark. This is more consistent with the streaming mode and makes it easier to run, say, a `spark-submit` wrapper script that actually SSHs somewhere else and runs the script. Fixes #1852.
Also added a `spark_deploy_mode` option (fixes #1864).
> upload py_files, Spark cluster mode

- mrjob/job.py
- mrjob/launch.py
- tests/test_job.py
Unlike `optparse`, `argparse` prepends `usage: ` to your usage string automatically. Fixes #1866
> don't print "usage: usage: " in help message

- docs/guides/configs-all-runners.rst
- mrjob/options.py
- mrjob/runner.py
- tests/test_job.py
- tests/test_runner.py
Adds a `--local-tmp-dir` switch, which can be used to override the config file (including to just use the default temp dir, if set to empty string). Fixes #1870.
> add --local-tmp-dir switch

- docs/guides/writing-mrjobs.rst
- mrjob/bin.py
- mrjob/dataproc.py
- mrjob/emr.py
- mrjob/examples/mr_jar_step_example.py
- mrjob/hadoop.py
- mrjob/runner.py
- mrjob/step.py
- tests/mr_jar_with_generic_args.py
- tests/test_bin.py
- tests/test_emr.py
- tests/test_hadoop.py
It turns out that many Hadoop JARs either don't handle generic args (e.g. `-D`, `-libjars`) or don't handle them as the first arguments after `jar`. See #1863 (which this fixes).
After this change, you'll need to explicitly use `mrjob.step.GENERIC_ARGS` to interpolate `-D` and `-libjars` into `JarStep`s. See `mrjob/examples/mr_jar_step_example.py` for an example of how to use `GENERIC_ARGS`.
> don't automatically add generic args to JarSteps

- docs/guides/configs-all-runners.rst
- mrjob/job.py
- mrjob/options.py
- mrjob/runner.py
- tests/test_job.py
- tests/test_runner.py
For historical reasons involving supporting non-Python languages, `MRJob`s don't directly report their step definition to the runner, instead relying on the runner to invoke your `MRJob` script with `--steps`. Fixes #1845.
Deprecated `steps_python_bin` as well (fixes #1851).
This change makes it so `MRJob` passes *steps* to `MRJobRunner`'s constructor. The code to support loading steps by invoking the script still exists, but is deprecated and should go away in the next major version.
If you have a `MRJob` script that doesn't actually run tasks (it's just a definition of JARs, command steps, etc.), you can get away without using passthru options and instead just using `self.arg_parser.add_argument()`. I didn't make a note of this in the documentation because it's kind of an edge case, but …
> job pushes steps to runner

- docs/guides/configs-all-runners.rst
- mrjob/options.py
This deprecates the `interpreter` and `steps_intepreter` options which are rarely (never?) used. Fixes #1850.
> Deprecate interpreter options

- docs/guides/configs-all-runners.rst
- docs/guides/configs-hadoopy-runners.rst
- docs/guides/emr-opts.rst
- docs/guides/spark.rst
- mrjob/job.py
- mrjob/options.py
- mrjob/step.py
- tests/test_bin.py
- tests/test_emr.py
- tests/test_emr_pooling.py
- tests/test_hadoop.py
- tests/test_job.py
- tests/test_sim.py
- tests/tools/emr/test_create_cluster.py
This adds `--applications`, `--archives`, `--dirs`, `--files`, `--libjars`, and `--py-files`, and deprecates their singular equivalents (except for `--application`, which is just an alternate name for `--applications`). Fixes #1882
> add plural switches

- mrjob/tools/diagnose.py
- mrjob/tools/emr/audit_usage.py
- mrjob/tools/emr/create_cluster.py
- mrjob/tools/emr/mrboss.py
- mrjob/tools/emr/report_long_jobs.py
- mrjob/tools/emr/s3_tmpwatch.py
- mrjob/tools/emr/terminate_cluster.py
- mrjob/tools/emr/terminate_idle_clusters.py
Added the subcommand name to the `--help` message for subcommands to the mrjob binary. Fixes #1885.
> Fixed usage in mrjob subcommand help messages

- docs/guides/cmd.rst
- mrjob/cmd.py
- mrjob/hadoop.py
- mrjob/launch.py
- mrjob/options.py
- mrjob/runner.py
- mrjob/step.py
- mrjob/tools/spark-submit-notes.txt
- mrjob/tools/spark_submit.py
- tests/test_cmd.py
- tests/test_job.py
- tests/tools/test_spark_submit.py
This creates a drop-in replacement for `spark-submit` that's capable of launching Spark jobs on EMR. Fixes #1382.
Also removed an extraneous option from the Hadoop runner (see #1899).
> add mrjob spark-submit subcommand

- docs/guides/runners.rst
- mrjob/compat.py
The existing links were returning a 404, corrected them.
> Minor correction for Hadoop documentation URLs.

- mrjob/emr.py
- mrjob/runner.py
- tests/mock_boto3/case.py
- tests/mock_boto3/s3.py
- tests/test_emr.py
Input path check now fails if any input "files" on S3 are archived in Glacier, as EMR is unable to read them and will fail with a rather cryptic Java error. Fixes #1887.
> Check if input paths are in Glacier

- mrjob/emr.py
- tests/mock_boto3/case.py
- tests/mock_boto3/s3.py
- tests/test_emr.py
This addresses an issue with Pull Request #1904: normally we want to reject input with the `GLACIER` storage class, but not if it's been restored from Glacier. Fixes #1884.
> allow input on S3 that's been restored from Glacier

- mrjob/bootstrap/terminate_idle_cluster_emr.sh
Use `/mnt/var/log/...` because `/var/log` doesn't exist on 2.x AMIs.
Hand-tested this on 2.x, 3.x, 4.x, and 5.x AMIs, all correctly shut themselves down.
I don't see much point in unit-testing this because it's a static script.
> fix idle-timeout script on 2.x AMIs

- mrjob/bin.py
- mrjob/dataproc.py
- mrjob/emr.py
- mrjob/hadoop.py
- mrjob/runner.py
- tests/mock_boto3/emr.py
- tests/test_inline.py
- tests/test_runner.py
This fixes a warning that happened (#1911) when we initialized a runner without setting `mr_job_script`, even when we didn't intend to run it.
Updated `_check_steps()` to ensure that if we initialize a runner with no `mr_job_script`, only steps that don't require a MRJob script are allowed.
Finally, raise ValueErrors rather than AssertionErrors (fixes #1877).
> clean up logic for runners with no mrjob script

- mrjob/dataproc.py
- mrjob/emr.py
- mrjob/hadoop.py
- mrjob/inline.py
- mrjob/runner.py
- mrjob/sim.py
- tests/mockhadoop.py
- tests/test_bin.py
- tests/test_dataproc.py
- tests/test_hadoop.py
- tests/test_inline.py
- tests/test_local.py
- tests/test_runner.py
Made `_check_steps()` much more robust. This keeps sim runners from pretending to run non-streaming step types (#1915), keeps the inline runner from trying and failing to run commands (#1878), and makes the Dataproc runner fail fast if passed Spark steps.
`_check_steps()` now raises `NotImplementedError` if it encounters steps unsupported by a particular runner, and `ValueError` if it encounters steps that don't make sense on any runner.
> catch bad steps on runner initialization

- mrjob/launch.py
- mrjob/runner.py
- tests/test_job.py
- tests/test_runner.py
Runners now log an "Unexpected option" warning if you use a command-line switch that corresponds to an option it doesn't support. Fixes #1898.
Also added unit tests for this warning.
> warn about command-line opts for the wrong runner

- mrjob/cloud.py
- tests/test_emr.py
Cloud runners need to kill the SSH tunnel process on cleanup. On some Windows installations, SIGKILL doesn't exist, so use SIGABRT instead. Fixes #1892.
> fall back to SIGABRT when SIGKILL unavailable

- docs/guides/configs-all-runners.rst
- mrjob/bin.py
- mrjob/dataproc.py
- tests/test_bin.py
- tests/test_hadoop.py
For local and Hadoop runners it was just `sh -ex`, which is tricky to use in a shebang (see #1376). Fixes #1924.
`/bin/sh` is considered compatible across platforms, so this change shouldn't break anything.
> default sh_bin to /bin/sh -ex in all runners

- docs/guides/configs-all-runners.rst
- mrjob/bin.py
- mrjob/runner.py
- mrjob/step.py
- mrjob/tools/spark_submit.py
- tests/test_bin.py
- tests/tools/test_spark_submit.py
This makes `--setup` work when running Spark on YARN by wrapping the Python binary. Fixes #1376.
> Spark setup scripts on YARN

- .travis.yml
- mrjob/bin.py
- mrjob/dataproc.py
- mrjob/hadoop.py
- mrjob/inline.py
- mrjob/logs/history.py
- mrjob/parse.py
- mrjob/py2.py
- mrjob/tools/emr/audit_usage.py
- mrjob/tools/spark_submit.py
This fixes some warnings that came up in Python 3.7. Fixes #1920.
This also updates the Travis CI config to run unit tests on a non-dev version of Python 3.7.
> fix deprecated escape sequences in regexes and docstrings

- mrjob/fs/s3.py
- tests/mock_boto3/s3.py
This fixes an API error that started happening when creating buckets with no location constraint. Fixes #1927.
> fix bucket creation on us-east-1

- mrjob/job.py
- spark/mrjob_spark_harness.py
- tests/test_job.py
This change creates a basic harness to run a MRJob in Spark (see #1941) and includes a couple of hooks in `MRJob` which de-couple the mapper/reducer logic from I/O (#1947).
We don't currently have a good way to unit-test the harness, so for now it's "experimental".
Also fixes #1846 (outdated comments about strict protocols).
> add experimental MRJob Spark harness

- mrjob/spark/mrjob_spark_harness.py
Fixes #1943.
This was hand-tested with real jobs. The ability to write automated tests was just recently added to MRJob (see #1361). Added a note to #1948, the ticket for missing Spark harness tests.
> allow output compression in spark harness

- mrjob/bin.py
- mrjob/inline.py
- mrjob/local.py
- mrjob/sim.py
- tests/sandbox.py
- tests/test_inline.py
The inline runner can now run `SparkSteps` inline, which allows us to write reasonably fast Spark unit tests. Fixes #1965.
This change also sets up a fake "working directory", much like we do when simulating Hadoop, so that it's possible to fully test the Spark harness quickly.
> add SparkStep support to inline runner

- mrjob/spark/mr_spark_harness.py
- mrjob/spark/mrjob_spark_harness.py
- tests/spark/test_mrjob_spark_harness.py
#1942 
Setting nargs=argparse.REMAINDER which seems to be the easiest way. 
However, the drawback is that the ordering of the passthrough argument would be important. 
'spark_harness_script.py class input output --compression-codec-class compression.class --remaining args --remaining --options'
will have correct compression-codec-class 
but 
'spark_harness_script.py class input output --remaining args --remaining --options --compression-codec-class compression.class'
will have --compression-codec-class compression.class in the passthru_args. 
I am not sure if this is acceptable. Let me know what you think. Thanks!
> spark_harness support passthrough arguments

- mrjob/dataproc.py
- mrjob/emr.py
- mrjob/fs/base.py
- mrjob/fs/composite.py
- mrjob/fs/gcs.py
- mrjob/fs/hadoop.py
- mrjob/fs/local.py
- mrjob/fs/s3.py
- mrjob/hadoop.py
- tests/fs/test_composite.py
- tests/fs/test_gcs.py
- tests/fs/test_hadoop.py
- tests/fs/test_local.py
- tests/fs/test_s3.py
Fixes #1977. This implements `put()` in every fs except the SSH filesystem, where we probably won't need it (see #1982).
> add put() to filesystem

- mrjob/inline.py
- mrjob/parse.py
- mrjob/py2.py
- mrjob/runner.py
- mrjob/sim.py
- tests/test_parse.py
- tests/test_runner.py
Apparently, some Spark installations treat input and output paths as local paths, and others treat them as HDFS paths (even when running in the local master). We now use `file:///` URIs instead of unqualified paths. Fixes #1985.
> pass file:/// URIs to Spark for input and output

- mrjob/spark/mr_spark_harness.py
- mrjob/spark/mrjob_spark_harness.py
- tests/mr_doubler.py
- tests/mr_streaming_and_spark.py
- tests/spark/test_mrjob_spark_harness.py
Added `--start-step` and `--end-step` arguments to the Spark harness, so it can deal gracefully with jobs with mixed step types. Fixes #1950.
Also simplified the code in `MRSparkHarness` that passes arguments straight through to the Spark harness, so we don't have to keep switches in sync in three different places.
> Spark harness can run a range of steps

- mrjob/spark/mrjob_spark_harness.py
- tests/mr_word_freq_count_with_combiner_cmd.py
- tests/spark/test_mrjob_spark_harness.py
This ensures that the Spark harness doesn't inadvertently re-partition after it groups together key-value pairs for the reducer. Fixes #1973.
Also fixed and tested a loose end: the spark harness can handle combiners that run commands, but it does so by skipping them.
> spark harness preserves partitioning

- mrjob/bin.py
- mrjob/inline.py
- mrjob/job.py
- mrjob/runner.py
- mrjob/sim.py
- mrjob/spark/mr_spark_harness.py
- mrjob/spark/mrjob_spark_harness.py
- mrjob/spark/runner.py
- mrjob/step.py
- mrjob/util.py
- tests/mr_streaming_and_spark.py
- tests/py2.py
- tests/spark/test_mrjob_spark_harness.py
- tests/spark/test_runner.py
- tests/test_bin.py
This change adds the magic glue between the Spark runner and the Spark harness, so that the Spark runner can run "classic" Hadoop streaming jobs in Spark. Fixes #1972.
> make spark runner run Hadoop streaming steps

- tests/test_runner.py
cat_output() now imitates Hadoop's output format as fully as it can without choking on non-hidden subdirectories. Fixes #1337.
Though honestly, it was already fixed by #1962; this just adds extensive tests, now that we're confident which behavior we want.
> fully test cat_output()

- mrjob/emr.py
- tests/test_emr.py
Fixes a bug that made it impossible to turn off subnets on the command line if you specified them in your config file. `--subnet ''` once again means don't use a VPC. Fixes #1931.
> --subnet '' means no subnet

- mrjob/fs/gcs.py
- tests/fs/test_gcs.py
`local_tmp_dir` was a temporary shim used by `GCSFilesystem` that no longer does anything. This change stops storing `local_tmp_dir` and issues a deprecation warning if it's set. Fixes #1961.
> deprecate local_tmp_dir in GCSFilesystem

- mrjob/bin.py
- mrjob/dataproc.py
- mrjob/emr.py
- mrjob/hadoop.py
- tests/test_bin.py
- tests/test_dataproc.py
- tests/test_emr.py
- tests/test_hadoop.py
- tests/test_local.py
Carefully updated the handling of every `*_bin` option so that if you set it to an empty value (e.g. `--sh-bin ''`) it uses the default.
This keeps us from having binaries with zero arguments (which can lead to weird results), and gives a convenient way to say, ignore the config file, just use the default.
Fixes #1926
> empty *_bin opt always means to use the default

- docs/guides/cloud-opts.rst
- mrjob/cloud.py
- mrjob/parse.py
- tests/test_emr.py
This change allows you to set API parameters to `RunJobFlow` (or the Google Cloud Dataproc equivalent) *inside* other parameter dictionaries. For example, you can use ``--extra-cluster-param Instances.EmrManagedMasterSecurityGroup=sg-foo`` to set a managed security group, without perturbing all the other parameters in the ``Instances`` dict. Fixes #1934.
> nested extra_cluster_params

- mrjob/bin.py
- mrjob/dataproc.py
- mrjob/emr.py
- mrjob/hadoop.py
- mrjob/inline.py
- mrjob/runner.py
- tests/test_bin.py
- tests/test_runner.py
This moves `_spark_script_args()` (and most of the argument interpolation code) into the base runner. Fixes #1967.
> move _spark_script_args() into base runner

- mrjob/bin.py
- mrjob/hadoop.py
- mrjob/spark/runner.py
- tests/test_bin.py
Prior to this change, we set environment variables in `spark.yarn.appMasterEnv.*` "just in case" we were on YARN. We now only do it if `_spark_master()` is `yarn`. Fixes #1919.
Related, mrjob will always pass `--master` and `--deploy-mode` to `spark-submit` — setting the corresponding options to empty values just uses the default.
> only set spark.yarn.appMasterEnv.* on YARN

- mrjob/emr.py
- tests/test_emr.py
This splits up `_usable_clusters` into two functions `_compare_cluster_setup` and `_check_cluster_state`. The original function would check that every aspect of the cluster are within the desired restraints. However this requires us to re-describe the setup of each cluster on each subsequent pooling attempt. This this setup doesn't change we are making superfluous EMR API calls, potentially causing more throttling. As such I split out the static setup checks into `_compare_cluster_setup` and the dynamic step checks into `_check_cluster_state` and only call `_check_cluster_state` when looking for a cluster in the second pass. This should greatly reduce the number of EMR API calls.
> Reduce EMR API calls in cluster pooling

- mrjob/dataproc.py
- mrjob/fs/gcs.py
- setup.py
- tests/mock_google/case.py
- tests/mock_google/storage.py
- tests/test_dataproc.py
This removes a weird, roundabout way of setting bucket location and instead does it a straightforward way (now that it's available in version 1.11.0). Fixes #2019.
> upgrade google-cloud-services to 1.11.0, remove shim

- mrjob/spark/runner.py
- tests/spark/test_runner.py
The Spark runner's constructor ignores some keyword args (`hadoop_input_format`, `hadoop_output_format`, `sort_values`) that are redundant when you can actually look at the job class (which it does, through the harness). This makes it explicit in the constructor's docstring and nails it down with a unit test. Fixes #2022.
> note that Spark runner ignores some kwargs

- mrjob/dataproc.py
- mrjob/emr.py
- mrjob/fs/base.py
- mrjob/fs/composite.py
- mrjob/fs/gcs.py
- mrjob/fs/hadoop.py
- mrjob/fs/local.py
- mrjob/fs/s3.py
- mrjob/runner.py
- tests/fs/test_composite.py
- tests/fs/test_gcs.py
- tests/fs/test_s3.py
- tests/test_dataproc.py
- tests/test_emr.py
`part_size` (for multi-part upload on S3 and GCS) is now set when filesystems are initialized. Also removed unnecessary shim methods for uploading, and moved the code for determining part size into `mrjob.runner`.
This is a mid-release change, so there's no issue number, but this is relevant to #1977 (adding `put()` to fs).
> remove part_size kwarg from fs.put()

- mrjob/dataproc.py
- mrjob/emr.py
- mrjob/fs/gcs.py
- mrjob/fs/s3.py
- mrjob/hadoop.py
- mrjob/runner.py
- mrjob/spark/runner.py
- tests/fs/test_gcs.py
- tests/fs/test_s3.py
- tests/mock_boto3/s3.py
- tests/test_dataproc.py
- tests/test_emr.py
`fs.mkdir()` will now implicitly create buckets on the GCS and S3 filesystems. Region and (on GCS) object TTL are now set at fs init time. Fixes #1953.
This change allowed us to simplify a fair amount of runner code having to do with creating buckets and uploading files.
> fs.mkdir() creates buckets

- mrjob/options.py
- mrjob/spark/runner.py
- tests/test_job.py
The Spark runner supports all filesystems, and needs to have platform-specific names for options that are usually generic (e.g. `gcs_region`, `s3_region`), but we forgot to add these options to `mrjob/option.py`.
Added a regression test to ensure we don't do this in the future. Also tweaked the option names used by the Spark runner to be more consistent with existing options.
> add missing spark runner options

- mrjob/cloud.py
- mrjob/emr.py
- mrjob/fs/s3.py
- mrjob/spark/runner.py
- tests/fs/test_s3.py
- tests/mock_boto3/s3.py
- tests/test_emr.py
This fixes a bug I introduced when I moved uploading out of the EMR runner and into the S3 filesystem (see #1977).  Basically, if you tell boto3 you want a part size of 0 or `None`, it causes a `TypeError`. Fixes #2033.
Also used the same default part size (100 MB) on the Spark runner that we do on Dataproc and EMR.
As noted in #2033, this is a non-issue for Google Cloud Storage, which falls back on a "resumable" upload if you don't set part size.
> fix part_size=0 on S3, default Spark part size to 100 MB

- mrjob/bin.py
- tests/test_bin.py
- tests/test_emr.py
- tests/test_hadoop.py
This change re-orders the arguments to `spark-submit` so that switches like `--master` will override whatever's in `--conf`. Fixes #2032.
> mrjob options should override Spark --conf

- mrjob/bin.py
- mrjob/hadoop.py
- tests/test_bin.py
- tests/test_hadoop.py
mrjob prefers to run the `hadoop` and `spark-submit` binaries by opening up a PTY and forking (since they they generally flush their output more often). This fixes an issue where `os.execvpe()` can fail if the binary doesn't exist or can't be run, causing the child process (that only exists to become `hadoop`/`spark-submit`) to continue being Python, raising an exception and then doing cleanup actions (e.g. deleting temp dir) in parallel with the master process.
This change makes it so that if `os.execvpe()` fails, we instead `os._exit()`. Either way, the child process doesn't take on a life of its own.
Fixes #2024.
> don't keep running if os.execvpe() fails

- mrjob/inline.py
- mrjob/launch.py
- mrjob/spark/mrjob_spark_harness.py
- mrjob/util.py
- tests/mr_spark_method_wordcount.py
- tests/sandbox.py
- tests/test_bin.py
- tests/test_job.py
- tests/test_launch.py
- tests/test_util.py
You can write a Spark MRJob just by defining `spark()`, but on most runners, that `spark()` method can't pass other job methods to Spark because the job stores `sys.stdin` in `job.stdin` (and likewise for stdout and stderr).
This pull request makes `job.stdin`, `job.stdout`, and `job.stderr` into properties, so we never have to store filehandles in the job instance unless someone passed them in via `job.sandbox()` (this would be rare; usually `job.sandbox()` sets `job.std*` to `BytesIO`s, which are serializable).
As a result, we were able to stop using `job.sandbox()` in the Spark harness and inline runner; `job.sandbox()` is once again just for testing.
Fixes #2039.
> Ensure that Spark can serialize job methods

- mrjob/runner.py
- mrjob/sim.py
- tests/mr_spark_os_walk.py
- tests/mr_tower_of_powers.py
- tests/sandbox.py
- tests/spark/test_runner.py
- tests/test_inline.py
- tests/test_local.py
This handles an edge case where the local working mirror dir isn't a URI because we're running locally. The Spark runner can now upload files with a different name on a local-cluster master, and the local runner can do the same when running Spark scripts. Fixes #2017 
(Inline mode can also do this, but that's because it invokes pyspark from within a simulated working directory. Added a test for this, because it should work.)
> handle Spark working dir correctly on local-cluster master

- mrjob/bin.py
- mrjob/examples/mr_most_used_word.py
- mrjob/examples/mr_spark_most_used_word.py
- mrjob/inline.py
- mrjob/runner.py
- mrjob/spark/runner.py
- tests/spark/test_runner.py
- tests/test_bin.py
This makes file upload args (the ones that use `add_file_arg()`) work on local Spark masters. Fixes #2031.
Also pushed some Spark logic that was in `mrjob/bin.py` up into `mrjob/runner.py` and stopped creating a working dir mirror when there's no working directory.
> get file upload args working on local[*] master

- mrjob/launch.py
- mrjob/spark/harness.py
- mrjob/spark/runner.py
- tests/spark/test_harness.py
- tests/spark/test_runner.py
This gracefully handles an edge case: jobs that load files uploaded with file args at init time. This isn't best practice (much better to lazy-load files as needed), but it's something people do in practice and that they'd expect to work in the Spark runner's emulation. Fixes #2044.
To make this work, I had to add arguments to the Spark harness for hadoop formats, step description, and sort_values. This seems like fair game because all of these are passed to the runner by the original job instance. If these *aren't* passed in, the Spark harness can still get by (as long as it can initialize the job).
> harness can simulate jobs that it can't init in Spark driver

- mrjob/bin.py
- mrjob/hadoop.py
- mrjob/runner.py
- mrjob/spark/runner.py
- tests/spark/test_runner.py
- tests/test_bin.py
- tests/test_emr.py
- tests/test_runner.py
This turns on setup scripts on all Spark masters that give executors their own working dir (fixes #2048).
Also removed removed `_spark_files` and `_spark_archives` attributes from the runner. At this point, we put the same files in Spark's working directory that we would in Hadoop Streaming's; the only special case is local Spark masters, where we don't bother with `--files` and `--archives` at all.
> enable setup scripts on non-YARN Spark masters

- mrjob/runner.py
- tests/spark/test_runner.py
Fix essentially a typo that broke mrjob's ability to download a remote file and re-upload it using the same name (which we need to fully support file uploads on Spark). Added a fairly extensive test. Fixes #1922.
> fix re-uploading of renamed remote files

- mrjob/spark/harness.py
- tests/mr_counting_job.py
Fixes #2060.
The updated test `tests.spark.test_harness.SparkHarnessOutputComparisonTestCase.test_increment_counter` failed before the change to the harness, and now passes. The non-spark tests using MRCountingJob still pass.
> Match increment_counter arguments in spark harness with base job

- mrjob/options.py
- tests/test_launch.py
If someone does something like `self.add_passthrough_option(..., type=int)`, this now passes `type=int` through to argparse, rather than complaining that `int` isn't in its dictionary of strings. Fixes #2058.
> emulate type=<type> in optparse

- mrjob/dataproc.py
- mrjob/emr.py
- mrjob/hadoop.py
- mrjob/inline.py
- mrjob/runner.py
- mrjob/setup.py
- tests/test_bin.py
- tests/test_setup.py
This partially undoes a change in v0.6.8 that moved all working dir files and archives to the working dir mirror, where they're uploaded with the same name they're going to have in the job's working dir. Not only is this pointless (either Spark fully supports `--archives` or it ignores it), but it messes up archives on Hadoop because Hadoop rely's on the path's file extension to un-archive archives.
Fixes #2059.
> No archives in wd mirror

- docs/guides/spark-runner-opts.rst
- mrjob/examples/mr_count_lines_by_file.py
- mrjob/options.py
- mrjob/spark/harness.py
- mrjob/spark/runner.py
- tests/mr_count_lines_by_filename.py
- tests/mr_spark_harness.py
- tests/spark/test_harness.py
- tests/spark/test_runner.py
This gives the Spark runner the ability to support jobs that use `jobconf_from_env('mapreduce.map.input.file')` to look at the name of the input file. Fixes #2061.
> add --emulate-map-input-file

- mrjob/sim.py
- tests/spark/test_harness.py
- tests/test_sim.py
This makes the sim runners better match Hadoop (and Spark). Fixes #2066.
> sim runners set mapreduce.map.input.file to a file:// URL

- mrjob/spark/runner.py
- tests/spark/test_runner.py
Adds a warning to try to catch a misunderstanding of the difference between `spark_tmp_dir` and `local_tmp_dir`. Fixes #2062.
> warn if spark_tmp_dir doesn't match master

- mrjob/tools/spark_submit.py
- tests/tools/test_spark_submit.py
You used to have to use `--` to make this possible. Fixes #2055.
> mrjob spark-submit can now pass switches to spark scripts

- mrjob/conf.py
- mrjob/py2.py
- tests/test_conf.py
For a long time, there has been a code path for loading mrjob's conf files in JSON if the YAML module is installed, but its error reporting didn't actually work. This change ensures the user gets a friendly, clear message if they try to load a (YAML) mrjob.conf without PyYAML installed. Fixes #2047.
> better error when loading conf file without PyYAML

- docs/guides/configs-all-runners.rst
- docs/guides/emr-bootstrap-cookbook.rst
- mrjob/bin.py
- mrjob/emr.py
- tests/test_bin.py
- tests/test_dataproc.py
- tests/test_emr.py
If you launch a mrjob script with PyPy, this sets the default python_bin used by Hadoop/Spark to PyPy as well. Fixes #1011.
> default python_bin can be pypy

- docs/guides/cloud-opts.rst
- mrjob/emr.py
- tests/test_emr.py
- tests/test_emr_pooling.py
This allows Spark to work on all AMIs, and works on all regions, even the new ones that don't allow `m4.large`, the previous default. Fixes #2071
> bump default instance type to m5.xlarge

- docs/guides/configs-all-runners.rst
- docs/guides/spark.rst
- mrjob/job.py
- mrjob/tools/spark_submit.py
- tests/spark/test_runner.py
- tests/test_bin.py
- tests/test_emr.py
- tests/test_inline.py
- tests/test_job.py
- tests/test_local.py
We moved over to `--files`, `--archives`, etc. in v0.6.7, but didn't update all of the docs or relevant tests. Fixes #2057
> don't treat --file etc. as canonical in docs and tests

- docs/guides/spark-runner-opts.rst
- mrjob/options.py
- mrjob/spark/harness.py
- mrjob/spark/runner.py
- tests/mr_sort_and_group_reversed_text.py
- tests/mr_spark_harness.py
- tests/spark/test_harness.py
- tests/spark/test_runner.py
This gives the Spark runner the ability to disable internal protocols and leave encoding and decoding data between job tasks and steps up to Spark. This should make any job run faster, but could break jobs that rely implicitly on the internal protocol in some way, so it's not enabled by default. Fixes #1952.
> add --skip-internal-protocol to Spark runner

- mrjob/launch.py
- tests/test_job.py
This uses `parse_intermixed_args()` to restore option-parsing behavior that went away when we switched from `optparse` to `argparse`. Only works in versions of Python that have `parse_intermixed_args()` (which is to say, Python 3.7 and later). Fixes #1701
> MRJobs take intermixed input file args in Python 3.7+

- mrjob/spark/runner.py
This makes it possible to use the Spark runner to run regular spark steps without needing to import `pyspark`, which may be in `spark-submit`'s PYTHONPATH without being in ours. Fixes #2091.
> Spark runner only imports spark harness for streaming steps

- .travis.yml
- README.rst
- setup.py
- tests/fs/test_gcs.py
- tests/spark/test_runner.py
- tests/test_bin.py
- tests/test_dataproc.py
This adds back official support for Python 3.4, so we can be sure that mrjob works on EMR AMIs that use Python 3.4. Fixes #2090.
There is not support for Google libraries or services in Python 3.4, as the recent Google libraries don't seem to support it. Python 3.4 has reached end-of-life earlier this year, so that shouldn't be much of a barrier to using mrjob with Google Cloud and Python 3.
> Re-enable Python 3.4

- docs/guides/emr-opts.rst
- mrjob/emr.py
- mrjob/runner.py
- tests/sandbox.py
- tests/test_dataproc.py
- tests/test_emr.py
This fixes a couple of bugs with the `emr_configurations` option. You can now override an earlier config with the same `Classification` (used to send both configs to EMR, causing an error). You may also simply clear out any existing configs with the `!clear` tag (which used to cause a crash).
Fixes #2097.
> override earlier emr_configurations

- docs/guides/cloud-opts.rst
- mrjob/emr.py
- tests/test_emr.py
In v0.6.10, we bumped the default instance type on EMR to ``m5.xlarge``. However, it turns out that only AMIs 5.13.0 and newer support this instance type. This change restores ``m4.large`` for earlier instance types. Fixes #2098 
This also bumps the default AMI to 5.27.0 (fixes #2105).
> restore m4.large for pre-5.13.0 AMIs, bump default AMI version

- mrjob/dataproc.py
- tests/test_dataproc.py
Bump the default image on Google Cloud Dataproc from 1.0 (which is no longer supported) to 1.3. Fixes #2110.
Note that the latest image version is 1.4; however, there is an issue with bootstrapping mrjob on the 1.4 images, see #2111.
> bump default image on Dataproc to 1.3

- mrjob/fs/base.py
- mrjob/fs/composite.py
- mrjob/fs/gcs.py
- mrjob/fs/hadoop.py
- mrjob/fs/local.py
- mrjob/fs/s3.py
- mrjob/fs/ssh.py
Args to FS method names were an inconsistent mess. Now that we're in a new series of versions (v0.7), we can rename them!
Fixes #1979
> make fs method args consistent

- .travis.yml
- setup.py
This means mrjob can install with less dependencies if people aren't using Google or AWS. Fixes #1935.
This also fixes a problem with the `rapidjson` entry in `extras_require` (fixes #2120), and adds `simplejson` to `extras_require`.
> move google and aws deps to extras_require

- docs/guides/testing.rst
- docs/guides/writing-mrjobs.rst
- mrjob/job.py
- mrjob/runner.py
- tests/examples/test_mr_most_used_word.py
- tests/examples/test_mr_phone_to_url.py
- tests/examples/test_mr_word_freq_count.py
- tests/test_job.py
- tests/test_runner.py
Initializing a `MRJob` without arguments or with `args=None` now makes it read args from `sys.argv[1:]` (it used to mean the same thing as `[]`). Fixes #2124 
This is theoretically a breaking change, but it should probably only affect testing, as `MRJobs` are usually either initialized by `run()` or with arguments. This follows up on getting rid of `MRJobLauncher` (see #2088).
Also removed the deprecated `stream_output()` (which I thought I had in a previous branch) and references to it.
> initializing a MRJob with no args means to read from sys.argv

- CHANGES.txt
- mrjob/pool.py
- mrjob/tools/emr/audit_usage.py
- tests/test_pool.py
- tests/tools/emr/test_audit_usage.py
`mrjob audit-emr-usage` no longer reads pool names from clusters launched by pre-0.6.0 versions of mrjob. Fixes #1815.
> stop reading pre-v0.6.0 pool names

- mrjob/emr.py
- tests/test_emr_pooling.py
Check the contents of archives used in bootstrapping to ensure that clusters have the same setup. Fixes #2136.
Also, the original path of files and archives no longer matters when creating the bootstrap hash, just the name and contents.
> add archives to pool hash

- docs/guides/cloud-opts.rst
- mrjob/cloud.py
- tests/test_emr.py
Make something like this:
```
runners:
emr:
extra_cluster_params:
Instances:
EmrManagedMasterSecurityGroup: sg-00000000000000000
```
add `EmrManagedMasterSecurityGroup` to the `Instances` API parameter, rather than clobbering it.
Fixes #2154.
> recursively merge extra_cluster_params

- docs/guides/configs-all-runners.rst
- mrjob/bin.py
- mrjob/emr.py
- tests/test_bin.py
- tests/test_emr.py
Python 2 has reached end-of-life, so the default `python` binary is finally Python 3 on some systems (notably, EMR AMI 6.x). Fixes #2151.
`python_bin` on Python 3 still defaults to `python3`.
PyPy has a different naming convention, so the default binary for PyPy 2 is still `pypy`.
> default python_bin on Python 2 to 'python2'

- docs/guides/configs-all-runners.rst
- mrjob/bin.py
- mrjob/emr.py
- tests/test_bin.py
- tests/test_emr.py
It turns out that `python2` isn't as common a binary name as i though; this changes it to `python2.7`. This is a second try at fixing #2151, and supersedes pull request #2156.
This also allows us to remove a special case that was already defaulting python_bin to `python2.7` on some old AMIs.
> use 'python2.7' as default python_bin for Python 2

- mrjob/bin.py
/bin/sh points to dash on Ubuntu 18.04 LTS. The construct
{ VAR=1; } &>/dev/null
doesn't set VAR for dash but it does for bash. Previously the script
would (benignly?) succeed, regardless of python's exit code. Here is a
typical output prior to this patch:
+ set +e
+ python args ...
+
+ [ -ne 0 ]
manifest-setup.sh: 67: [: -ne: unexpected operator
+ rm ./input-jrOOHByJvm.blf
+ RETURNCODE=0
+ set +x
+ exit
> MRJobBinRunner: make script compatible with dash

- CHANGES.txt
- mrjob/spark/harness.py
- tests/spark/test_harness.py
Issue: #2176 
The proposed fix is to write to given local-file path using python file writer if the part-* (counters file) is not created on driver.
Additional (possible?) benefit of the fix is to avoid additional communication overhead (latency and network access) of spark harness to populate S3 bucket and spark driver retrieving content from the S3 bucket besides additional operations like deleting the bucket. I noticed with my test-runs that with given s3 path the job was hanging for a long time.
Other changes include flake error fixes.
> Write counters to local filepath when spark-tmp-dir is not an S3 path.

- README.rst
The original link on the README to the mrjob.conf documentation (http://packages.python.org/mrjob/guides/configs-basics.html) is a dead link.  I have updated it to https://mrjob.readthedocs.io/en/latest/guides/configs-basics.html
> Correct the link to the configuration documentation (README.rst).

- CHANGES.txt
- docs/guides/emr-opts.rst
- mrjob/emr.py
- mrjob/options.py
- tests/mock_boto3/emr.py
- tests/test_emr.py
- tests/test_emr_pooling.py
Now that EMR can run steps concurrently, it can be a problem to submit all of the steps of a multi-step job concurrently. This change makes it so that for AMIs that can run steps concurrently (5.28.0 and later), the runner submits multi-step jobs one step at a time. This behavior can be changed explicitly with the `add_steps_in_batch` option.
This is a first step toward full support for concurrent steps (#2185).
> add_steps_in_batch option

- docs/guides/emr-opts.rst
- mrjob/emr.py
- mrjob/options.py
- mrjob/pool.py
- tests/test_emr.py
- tests/test_emr_pooling.py
Cluster pooling tries to ensure jobs re-use existing clusters rather than creating their own. However, this can go wrong when multiple jobs start simultaneously (the "thundering herd" problem).
This patch creates the `max_clusters_in_pool` option (fixes #2192 ) to check if the pool is already "full" of clusters before creating one. If it is, the job will wait until a cluster is available to join or one or more clusters in the pool terminate. To handle the "thundering herd" problem, once we've determined that we're allowed to create a new cluster, we wait a random number of seconds and double-check. This is controlled by the `pool_jitter_seconds` option (fixes #2200).
The `pool_wait_minutes` option also handles the "thundering herd" problem badly, since every cluster will wait, even though …
> max_clusters_in_pool, pool_timeout_minutes, and bypassing of pool_wait_minutes
